// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/pkg/irpc"
)

type FileServerIRpcService struct {
	impl FileServer
}

func NewFileServerIRpcService(impl FileServer) *FileServerIRpcService {
	return &FileServerIRpcService{impl: impl}
}
func (FileServerIRpcService) Id() string {
	return "FileServerIRpcService"
}
func (s *FileServerIRpcService) GetFuncCall(funcId irpc.FuncId) (irpc.ArgDeserializer, error) {
	switch funcId {
	case 0: // ListFiles
		return func(d *irpc.Decoder) (irpc.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_FileServerListFilesReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpc.Serializable {
				// EXECUTE
				var resp _Irpc_FileServerListFilesResp
				resp.Param0_, resp.Param1_ = s.impl.ListFiles()
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

type FileServerIRpcClient struct {
	endpoint *irpc.Endpoint
	id       string
}

func NewFileServerIRpcClient(endpoint *irpc.Endpoint) (*FileServerIRpcClient, error) {
	id := "FileServerIRpcService"
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &FileServerIRpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *FileServerIRpcClient) ListFiles() ([]FileInfo, error) {
	var req = _Irpc_FileServerListFilesReq{}
	var resp _Irpc_FileServerListFilesResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		var zero _Irpc_FileServerListFilesResp
		return zero.Param0_, err
	}
	return resp.Param0_, resp.Param1_
}

type _Irpc_FileServerListFilesReq struct {
}

func (s _Irpc_FileServerListFilesReq) Serialize(e *irpc.Encoder) error {
	return nil
}
func (s *_Irpc_FileServerListFilesReq) Deserialize(d *irpc.Decoder) error {
	return nil
}

type _Irpc_FileServerListFilesResp struct {
	Param0_ []FileInfo
	Param1_ error
}

func (s _Irpc_FileServerListFilesResp) Serialize(e *irpc.Encoder) error {
	{ // s.Param0_
		var l int = len(s.Param0_)
		if err := e.VarInt(l); err != nil {
			return fmt.Errorf("serialize l of type 'int': %w", err)
		}

		for i := 0; i < l; i++ {
			if err := e.UvarInt64(s.Param0_[i].FileSize); err != nil {
				return fmt.Errorf("serialize s.Param0_[i].FileSize of type 'uint64': %w", err)
			}

		}
	}
	{
		var isNil bool
		if s.Param1_ == nil {
			isNil = true
		}
		if err := e.Bool(isNil); err != nil {
			return fmt.Errorf("serialize isNil of type 'bool': %w", err)
		}

		if !isNil {
			{ // Error()
				_Error_0_ := s.Param1_.Error()
				if err := e.String(_Error_0_); err != nil {
					return fmt.Errorf("serialize _Error_0_ of type 'string': %w", err)
				}
			}
		}
	}
	return nil
}
func (s *_Irpc_FileServerListFilesResp) Deserialize(d *irpc.Decoder) error {
	{ // s.Param0_
		var l int
		if err := d.VarInt(&l); err != nil {
			return fmt.Errorf("deserialize l of type 'int': %w", err)
		}

		s.Param0_ = make([]FileInfo, l)
		for i := 0; i < l; i++ {
			if err := d.UvarInt64(&s.Param0_[i].FileSize); err != nil {
				return fmt.Errorf("deserialize s.Param0_[i].FileSize of type 'uint64': %w", err)
			}

		}
	}
	{
		var isNil bool
		if err := d.Bool(&isNil); err != nil {
			return fmt.Errorf("deserialize isNil of type 'bool': %w", err)
		}

		if isNil {
			s.Param1_ = nil
		} else {
			var impl _error_FileServer_irpcInterfaceImpl
			{ // Error()
				if err := d.String(&impl._Error_0_); err != nil {
					return fmt.Errorf("deserialize impl._Error_0_ of type 'string': %w", err)
				}
			}
			s.Param1_ = impl
		}
	}
	return nil
}

type _error_FileServer_irpcInterfaceImpl struct {
	_Error_0_ string
}

func (i _error_FileServer_irpcInterfaceImpl) Error() string {
	return i._Error_0_
}
