// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type basicAPIIrpcService struct {
	impl basicAPI
	id   []byte
}

func newBasicAPIIrpcService(impl basicAPI) *basicAPIIrpcService {
	return &basicAPIIrpcService{
		impl: impl,
		id: []byte{
			0x37, 0xe3, 0xee, 0x73, 0x5f, 0x07, 0x45, 0xcc,
			0x57, 0xe4, 0xc3, 0xb8, 0xfc, 0x89, 0xb9, 0x2e,
			0x52, 0x12, 0xfd, 0x3c, 0xae, 0x9d, 0x90, 0x3a,
			0x74, 0x79, 0xbf, 0x91, 0x59, 0x0d, 0x14, 0x08,
		},
	}
}
func (s *basicAPIIrpcService) Id() []byte {
	return s.id
}
func (s *basicAPIIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // addByte
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addByteReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addByteResp
				resp.p0 = s.impl.addByte(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 1: // addInt
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addIntReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addIntResp
				resp.p0 = s.impl.addInt(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 2: // swapInt
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_swapIntReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_swapIntResp
				resp.p0, resp.p1 = s.impl.swapInt(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 3: // subUint
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_subUintReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_subUintResp
				resp.p0 = s.impl.subUint(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 4: // addInt8
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addInt8Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addInt8Resp
				resp.p0 = s.impl.addInt8(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 5: // addUint8
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addUint8Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addUint8Resp
				resp.p0 = s.impl.addUint8(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 6: // addInt16
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addInt16Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addInt16Resp
				resp.p0 = s.impl.addInt16(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 7: // addUint16
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addUint16Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addUint16Resp
				resp.p0 = s.impl.addUint16(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 8: // addInt32
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addInt32Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addInt32Resp
				resp.p0 = s.impl.addInt32(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 9: // addUint32
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addUint32Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addUint32Resp
				resp.p0 = s.impl.addUint32(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 10: // addInt64
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addInt64Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addInt64Resp
				resp.p0 = s.impl.addInt64(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 11: // addUint64
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addUint64Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addUint64Resp
				resp.p0 = s.impl.addUint64(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 12: // addFloat64
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addFloat64Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addFloat64Resp
				resp.p0 = s.impl.addFloat64(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 13: // addFloat32
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_addFloat32Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_addFloat32Resp
				resp.p0 = s.impl.addFloat32(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 14: // toUpper
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_toUpperReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_toUpperResp
				resp.p0 = s.impl.toUpper(args.c)
				return resp
			}, nil
		}, nil
	case 15: // toUpperString
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_toUpperStringReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_toUpperStringResp
				resp.p0 = s.impl.toUpperString(args.s)
				return resp
			}, nil
		}, nil
	case 16: // negBool
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_basicAPI_negBoolReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_basicAPI_negBoolResp
				resp.p0 = s.impl.negBool(args.ok)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// basicAPIIrpcClient implements basicAPI
//
// basicAPI tests types.Basic types
// and this is a two line description
type basicAPIIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newBasicAPIIrpcClient(endpoint irpcgen.Endpoint) (*basicAPIIrpcClient, error) {
	id := []byte{
		0x37, 0xe3, 0xee, 0x73, 0x5f, 0x07, 0x45, 0xcc,
		0x57, 0xe4, 0xc3, 0xb8, 0xfc, 0x89, 0xb9, 0x2e,
		0x52, 0x12, 0xfd, 0x3c, 0xae, 0x9d, 0x90, 0x3a,
		0x74, 0x79, 0xbf, 0x91, 0x59, 0x0d, 0x14, 0x08,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &basicAPIIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *basicAPIIrpcClient) addByte(a byte, b byte) byte {
	var req = _irpc_basicAPI_addByteReq{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addByteResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addInt(a int, b int) int {
	var req = _irpc_basicAPI_addIntReq{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addIntResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// multiple return values
func (_c *basicAPIIrpcClient) swapInt(a int, b int) (int, int) {
	var req = _irpc_basicAPI_swapIntReq{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_swapIntResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0, resp.p1
}
func (_c *basicAPIIrpcClient) subUint(a uint, b uint) uint {
	var req = _irpc_basicAPI_subUintReq{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_subUintResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addInt8(a int8, b int8) int8 {
	var req = _irpc_basicAPI_addInt8Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addInt8Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 4, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addUint8(a uint8, b uint8) uint8 {
	var req = _irpc_basicAPI_addUint8Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addUint8Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addInt16(a int16, b int16) int16 {
	var req = _irpc_basicAPI_addInt16Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addInt16Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 6, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addUint16(a uint16, b uint16) uint16 {
	var req = _irpc_basicAPI_addUint16Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addUint16Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 7, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addInt32(a int32, b int32) int32 {
	var req = _irpc_basicAPI_addInt32Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addInt32Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 8, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addUint32(a uint32, b uint32) uint32 {
	var req = _irpc_basicAPI_addUint32Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addUint32Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 9, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addInt64(a int64, b int64) int64 {
	var req = _irpc_basicAPI_addInt64Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addInt64Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 10, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addUint64(a uint64, b uint64) uint64 {
	var req = _irpc_basicAPI_addUint64Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addUint64Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 11, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addFloat64(a float64, b float64) float64 {
	var req = _irpc_basicAPI_addFloat64Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addFloat64Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 12, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) addFloat32(a float32, b float32) float32 {
	var req = _irpc_basicAPI_addFloat32Req{
		a: a,
		b: b,
	}
	var resp _irpc_basicAPI_addFloat32Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 13, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) toUpper(c rune) rune {
	var req = _irpc_basicAPI_toUpperReq{
		c: c,
	}
	var resp _irpc_basicAPI_toUpperResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 14, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) toUpperString(s string) string {
	var req = _irpc_basicAPI_toUpperStringReq{
		s: s,
	}
	var resp _irpc_basicAPI_toUpperStringResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 15, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *basicAPIIrpcClient) negBool(ok bool) bool {
	var req = _irpc_basicAPI_negBoolReq{
		ok: ok,
	}
	var resp _irpc_basicAPI_negBoolResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 16, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_basicAPI_addByteReq struct {
	a byte
	b byte
}

func (s _irpc_basicAPI_addByteReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"byte\": %w", err)
	}
	if err := e.Uint8(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"byte\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addByteReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"byte\": %w", err)
	}
	if err := d.Uint8(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"byte\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addByteResp struct {
	p0 byte
}

func (s _irpc_basicAPI_addByteResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"byte\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addByteResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"byte\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addIntReq struct {
	a int
	b int
}

func (s _irpc_basicAPI_addIntReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int\": %w", err)
	}
	if err := e.VarInt(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addIntReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addIntResp struct {
	p0 int
}

func (s _irpc_basicAPI_addIntResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addIntResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_swapIntReq struct {
	a int
	b int
}

func (s _irpc_basicAPI_swapIntReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int\": %w", err)
	}
	if err := e.VarInt(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_swapIntReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_swapIntResp struct {
	p0 int
	p1 int
}

func (s _irpc_basicAPI_swapIntResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	if err := e.VarInt(s.p1); err != nil {
		return fmt.Errorf("serialize s.p1 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_swapIntResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.p1); err != nil {
		return fmt.Errorf("deserialize s.p1 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_subUintReq struct {
	a uint
	b uint
}

func (s _irpc_basicAPI_subUintReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"uint\": %w", err)
	}
	if err := e.UvarInt(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"uint\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_subUintReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"uint\": %w", err)
	}
	if err := d.UvarInt(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"uint\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_subUintResp struct {
	p0 uint
}

func (s _irpc_basicAPI_subUintResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"uint\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_subUintResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"uint\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt8Req struct {
	a int8
	b int8
}

func (s _irpc_basicAPI_addInt8Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.Int8(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int8\": %w", err)
	}
	if err := e.Int8(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int8\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt8Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Int8(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int8\": %w", err)
	}
	if err := d.Int8(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int8\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt8Resp struct {
	p0 int8
}

func (s _irpc_basicAPI_addInt8Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Int8(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int8\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt8Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Int8(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int8\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint8Req struct {
	a uint8
	b uint8
}

func (s _irpc_basicAPI_addUint8Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"uint8\": %w", err)
	}
	if err := e.Uint8(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint8Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"uint8\": %w", err)
	}
	if err := d.Uint8(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"uint8\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint8Resp struct {
	p0 uint8
}

func (s _irpc_basicAPI_addUint8Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint8Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"uint8\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt16Req struct {
	a int16
	b int16
}

func (s _irpc_basicAPI_addInt16Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt16(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int16\": %w", err)
	}
	if err := e.VarInt16(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int16\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt16Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt16(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int16\": %w", err)
	}
	if err := d.VarInt16(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int16\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt16Resp struct {
	p0 int16
}

func (s _irpc_basicAPI_addInt16Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt16(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int16\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt16Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt16(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int16\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint16Req struct {
	a uint16
	b uint16
}

func (s _irpc_basicAPI_addUint16Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt16(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"uint16\": %w", err)
	}
	if err := e.UvarInt16(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"uint16\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint16Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt16(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"uint16\": %w", err)
	}
	if err := d.UvarInt16(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"uint16\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint16Resp struct {
	p0 uint16
}

func (s _irpc_basicAPI_addUint16Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt16(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"uint16\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint16Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt16(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"uint16\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt32Req struct {
	a int32
	b int32
}

func (s _irpc_basicAPI_addInt32Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt32(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int32\": %w", err)
	}
	if err := e.VarInt32(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int32\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt32Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt32(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int32\": %w", err)
	}
	if err := d.VarInt32(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int32\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt32Resp struct {
	p0 int32
}

func (s _irpc_basicAPI_addInt32Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt32(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int32\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt32Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt32(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int32\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint32Req struct {
	a uint32
	b uint32
}

func (s _irpc_basicAPI_addUint32Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt32(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"uint32\": %w", err)
	}
	if err := e.UvarInt32(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"uint32\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint32Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt32(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"uint32\": %w", err)
	}
	if err := d.UvarInt32(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"uint32\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint32Resp struct {
	p0 uint32
}

func (s _irpc_basicAPI_addUint32Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt32(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"uint32\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint32Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt32(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"uint32\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt64Req struct {
	a int64
	b int64
}

func (s _irpc_basicAPI_addInt64Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt64(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int64\": %w", err)
	}
	if err := e.VarInt64(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int64\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt64Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt64(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int64\": %w", err)
	}
	if err := d.VarInt64(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int64\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addInt64Resp struct {
	p0 int64
}

func (s _irpc_basicAPI_addInt64Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt64(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int64\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addInt64Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt64(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int64\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint64Req struct {
	a uint64
	b uint64
}

func (s _irpc_basicAPI_addUint64Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt64(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"uint64\": %w", err)
	}
	if err := e.UvarInt64(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"uint64\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint64Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt64(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"uint64\": %w", err)
	}
	if err := d.UvarInt64(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"uint64\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addUint64Resp struct {
	p0 uint64
}

func (s _irpc_basicAPI_addUint64Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.UvarInt64(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"uint64\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addUint64Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.UvarInt64(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"uint64\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addFloat64Req struct {
	a float64
	b float64
}

func (s _irpc_basicAPI_addFloat64Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"float64\": %w", err)
	}
	if err := e.Float64le(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"float64\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addFloat64Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"float64\": %w", err)
	}
	if err := d.Float64le(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"float64\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addFloat64Resp struct {
	p0 float64
}

func (s _irpc_basicAPI_addFloat64Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"float64\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addFloat64Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"float64\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addFloat32Req struct {
	a float32
	b float32
}

func (s _irpc_basicAPI_addFloat32Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float32le(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"float32\": %w", err)
	}
	if err := e.Float32le(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"float32\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addFloat32Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float32le(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"float32\": %w", err)
	}
	if err := d.Float32le(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"float32\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_addFloat32Resp struct {
	p0 float32
}

func (s _irpc_basicAPI_addFloat32Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float32le(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"float32\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_addFloat32Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float32le(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"float32\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_toUpperReq struct {
	c rune
}

func (s _irpc_basicAPI_toUpperReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt32(s.c); err != nil {
		return fmt.Errorf("serialize s.c of type \"rune\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_toUpperReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt32(&s.c); err != nil {
		return fmt.Errorf("deserialize s.c of type \"rune\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_toUpperResp struct {
	p0 rune
}

func (s _irpc_basicAPI_toUpperResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt32(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"rune\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_toUpperResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt32(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"rune\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_toUpperStringReq struct {
	s string
}

func (s _irpc_basicAPI_toUpperStringReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.String(s.s); err != nil {
		return fmt.Errorf("serialize s.s of type \"string\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_toUpperStringReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.String(&s.s); err != nil {
		return fmt.Errorf("deserialize s.s of type \"string\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_toUpperStringResp struct {
	p0 string
}

func (s _irpc_basicAPI_toUpperStringResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.String(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"string\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_toUpperStringResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.String(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"string\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_negBoolReq struct {
	ok bool
}

func (s _irpc_basicAPI_negBoolReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.Bool(s.ok); err != nil {
		return fmt.Errorf("serialize s.ok of type \"bool\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_negBoolReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Bool(&s.ok); err != nil {
		return fmt.Errorf("deserialize s.ok of type \"bool\": %w", err)
	}
	return nil
}

type _irpc_basicAPI_negBoolResp struct {
	p0 bool
}

func (s _irpc_basicAPI_negBoolResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Bool(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}
func (s *_irpc_basicAPI_negBoolResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Bool(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}
