// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/binmarshal.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
	"time"
)

var _binMarshalIrpcId = []byte{
	0x7d, 0x5e, 0xb7, 0x84, 0xa8, 0x95, 0x43, 0xc6,
	0xc2, 0x6c, 0x17, 0xc5, 0x74, 0xf5, 0xdd, 0x91,
	0x2e, 0x99, 0xd8, 0xe8, 0x0d, 0x55, 0xa2, 0xda,
	0xbf, 0xb1, 0x1d, 0xff, 0x25, 0xd8, 0x97, 0x63,
}

// binMarshalIrpcService provides [binMarshal] interface over irpc
type binMarshalIrpcService struct {
	impl binMarshal
}

// newBinMarshalIrpcService returns new [irpcgen.Service] forwarding [binMarshal] network calls to impl
func newBinMarshalIrpcService(impl binMarshal) *binMarshalIrpcService {
	return &binMarshalIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *binMarshalIrpcService) Id() []byte {
	return _binMarshalIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *binMarshalIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // reflect
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_binMarshal_reflectReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_binMarshal_reflectResp
				resp.p0 = s.impl.reflect(args.t)
				return resp
			}, nil
		}, nil
	case 1: // addHour
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_binMarshal_addHourReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_binMarshal_addHourResp
				resp.p0 = s.impl.addHour(args.t)
				return resp
			}, nil
		}, nil
	case 2: // addMyHour
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_binMarshal_addMyHourReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_binMarshal_addMyHourResp
				resp.p0 = s.impl.addMyHour(args.t)
				return resp
			}, nil
		}, nil
	case 3: // addMyStructHour
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_binMarshal_addMyStructHourReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_binMarshal_addMyStructHourResp
				resp.p0 = s.impl.addMyStructHour(args.t)
				return resp
			}, nil
		}, nil
	case 4: // structPass
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_binMarshal_structPassReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_binMarshal_structPassResp
				resp.p0 = s.impl.structPass(args.st)
				return resp
			}, nil
		}, nil
	case 5: // myMarshalableStructPass
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_binMarshal_myMarshalableStructPassReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_binMarshal_myMarshalableStructPassResp
				resp.p0 = s.impl.myMarshalableStructPass(args.s)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// binMarshalIrpcClient implements [binMarshal] interface. It by forwards calls over network to [binMarshalIrpcService] that provides the implementation.
type binMarshalIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newBinMarshalIrpcClient(endpoint irpcgen.Endpoint) (*binMarshalIrpcClient, error) {
	if err := endpoint.RegisterClient(_binMarshalIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &binMarshalIrpcClient{endpoint: endpoint}, nil
}

// reflect implements [binMarshal]
//
func (_c *binMarshalIrpcClient) reflect(t time.Time) time.Time {
	var req = _irpc_binMarshal_reflectReq{
		t: t,
	}
	var resp _irpc_binMarshal_reflectResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _binMarshalIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// addHour implements [binMarshal]
func (_c *binMarshalIrpcClient) addHour(t time.Time) time.Time {
	var req = _irpc_binMarshal_addHourReq{
		t: t,
	}
	var resp _irpc_binMarshal_addHourResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _binMarshalIrpcId, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// addMyHour implements [binMarshal]
func (_c *binMarshalIrpcClient) addMyHour(t myTime) myTime {
	var req = _irpc_binMarshal_addMyHourReq{
		t: t,
	}
	var resp _irpc_binMarshal_addMyHourResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _binMarshalIrpcId, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// addMyStructHour implements [binMarshal]
func (_c *binMarshalIrpcClient) addMyStructHour(t myStructTime) myStructTime {
	var req = _irpc_binMarshal_addMyStructHourReq{
		t: t,
	}
	var resp _irpc_binMarshal_addMyStructHourResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _binMarshalIrpcId, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// structPass implements [binMarshal]
func (_c *binMarshalIrpcClient) structPass(st structContainingBinMarshallable) structContainingBinMarshallable {
	var req = _irpc_binMarshal_structPassReq{
		st: st,
	}
	var resp _irpc_binMarshal_structPassResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _binMarshalIrpcId, 4, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// myMarshalableStructPass implements [binMarshal]
func (_c *binMarshalIrpcClient) myMarshalableStructPass(s myMarshallableStruct) string {
	var req = _irpc_binMarshal_myMarshalableStructPassReq{
		s: s,
	}
	var resp _irpc_binMarshal_myMarshalableStructPassResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _binMarshalIrpcId, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_binMarshal_reflectReq struct {
	t time.Time
}

func (s _irpc_binMarshal_reflectReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.t); err != nil {
		return fmt.Errorf("serialize \"t\" of type time.Time: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_reflectReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.t); err != nil {
		return fmt.Errorf("deserialize t of type time.Time: %w", err)
	}
	return nil
}

type _irpc_binMarshal_reflectResp struct {
	p0 time.Time
}

func (s _irpc_binMarshal_reflectResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.p0); err != nil {
		return fmt.Errorf("serialize type time.Time: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_reflectResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type time.Time: %w", err)
	}
	return nil
}

type _irpc_binMarshal_addHourReq struct {
	t time.Time
}

func (s _irpc_binMarshal_addHourReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.t); err != nil {
		return fmt.Errorf("serialize \"t\" of type time.Time: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_addHourReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.t); err != nil {
		return fmt.Errorf("deserialize t of type time.Time: %w", err)
	}
	return nil
}

type _irpc_binMarshal_addHourResp struct {
	p0 time.Time
}

func (s _irpc_binMarshal_addHourResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.p0); err != nil {
		return fmt.Errorf("serialize type time.Time: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_addHourResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type time.Time: %w", err)
	}
	return nil
}

type _irpc_binMarshal_addMyHourReq struct {
	t myTime
}

func (s _irpc_binMarshal_addMyHourReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.t); err != nil {
		return fmt.Errorf("serialize \"t\" of type myTime: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_addMyHourReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.t); err != nil {
		return fmt.Errorf("deserialize t of type myTime: %w", err)
	}
	return nil
}

type _irpc_binMarshal_addMyHourResp struct {
	p0 myTime
}

func (s _irpc_binMarshal_addMyHourResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.p0); err != nil {
		return fmt.Errorf("serialize type myTime: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_addMyHourResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type myTime: %w", err)
	}
	return nil
}

type _irpc_binMarshal_addMyStructHourReq struct {
	t myStructTime
}

func (s _irpc_binMarshal_addMyStructHourReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.t); err != nil {
		return fmt.Errorf("serialize \"t\" of type myStructTime: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_addMyStructHourReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.t); err != nil {
		return fmt.Errorf("deserialize t of type myStructTime: %w", err)
	}
	return nil
}

type _irpc_binMarshal_addMyStructHourResp struct {
	p0 myStructTime
}

func (s _irpc_binMarshal_addMyStructHourResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBinaryMarshaler(e, s.p0); err != nil {
		return fmt.Errorf("serialize type myStructTime: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_addMyStructHourResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBinaryUnmarshaler(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type myStructTime: %w", err)
	}
	return nil
}

type _irpc_binMarshal_structPassReq struct {
	st structContainingBinMarshallable
}

func (s _irpc_binMarshal_structPassReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, s structContainingBinMarshallable) error {
		if err := irpcgen.EncBinaryMarshaler(enc, s.t); err != nil {
			return fmt.Errorf("serialize s.t of type time.Time: %w", err)
		}
		return nil
	}(e, s.st); err != nil {
		return fmt.Errorf("serialize \"st\" of type structContainingBinMarshallable: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_structPassReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *structContainingBinMarshallable) error {
		if err := irpcgen.DecBinaryUnmarshaler(dec, &s.t); err != nil {
			return fmt.Errorf("deserialize s.t of type time.Time: %w", err)
		}
		return nil
	}(d, &s.st); err != nil {
		return fmt.Errorf("deserialize st of type structContainingBinMarshallable: %w", err)
	}
	return nil
}

type _irpc_binMarshal_structPassResp struct {
	p0 structContainingBinMarshallable
}

func (s _irpc_binMarshal_structPassResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, s structContainingBinMarshallable) error {
		if err := irpcgen.EncBinaryMarshaler(enc, s.t); err != nil {
			return fmt.Errorf("serialize s.t of type time.Time: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type structContainingBinMarshallable: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_structPassResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *structContainingBinMarshallable) error {
		if err := irpcgen.DecBinaryUnmarshaler(dec, &s.t); err != nil {
			return fmt.Errorf("deserialize s.t of type time.Time: %w", err)
		}
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type structContainingBinMarshallable: %w", err)
	}
	return nil
}

type _irpc_binMarshal_myMarshalableStructPassReq struct {
	s myMarshallableStruct
}

func (s _irpc_binMarshal_myMarshalableStructPassReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, s myMarshallableStruct) error {
		if err := irpcgen.EncString(enc, s.str); err != nil {
			return fmt.Errorf("serialize s.str of type string: %w", err)
		}
		return nil
	}(e, s.s); err != nil {
		return fmt.Errorf("serialize \"s\" of type myMarshallableStruct: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_myMarshalableStructPassReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *myMarshallableStruct) error {
		if err := irpcgen.DecString(dec, &s.str); err != nil {
			return fmt.Errorf("deserialize s.str of type string: %w", err)
		}
		return nil
	}(d, &s.s); err != nil {
		return fmt.Errorf("deserialize s of type myMarshallableStruct: %w", err)
	}
	return nil
}

type _irpc_binMarshal_myMarshalableStructPassResp struct {
	p0 string
}

func (s _irpc_binMarshal_myMarshalableStructPassResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	return nil
}
func (s *_irpc_binMarshal_myMarshalableStructPassResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	return nil
}
