// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/edgecases.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _emptyAPIIrpcId = []byte{
	0x8d, 0x0d, 0xce, 0x8f, 0xa2, 0x0c, 0x81, 0xeb,
	0x79, 0xc3, 0xbe, 0xe7, 0x77, 0xb6, 0x30, 0x78,
	0xe9, 0x46, 0x1c, 0x3f, 0xdd, 0x82, 0x6b, 0xfc,
	0xc0, 0xe6, 0xb0, 0x6a, 0x79, 0xc7, 0x3a, 0x84,
}

type emptyAPIIrpcService struct {
	impl emptyAPI
}

func newEmptyAPIIrpcService(impl emptyAPI) *emptyAPIIrpcService {
	return &emptyAPIIrpcService{
		impl: impl,
	}
}
func (s *emptyAPIIrpcService) Id() []byte {
	return _emptyAPIIrpcId
}
func (s *emptyAPIIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// emptyAPIIrpcClient implements emptyAPI
type emptyAPIIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newEmptyAPIIrpcClient(endpoint irpcgen.Endpoint) (*emptyAPIIrpcClient, error) {
	if err := endpoint.RegisterClient(_emptyAPIIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &emptyAPIIrpcClient{endpoint: endpoint}, nil
}

var _edgeCasesIrpcId = []byte{
	0x55, 0xa3, 0x33, 0x44, 0x68, 0xea, 0x40, 0x8f,
	0xd3, 0x73, 0x71, 0x5e, 0xcd, 0x3a, 0xf1, 0xda,
	0x01, 0xdb, 0x33, 0x4b, 0xd5, 0x24, 0x9f, 0xc8,
	0x6a, 0x4a, 0x07, 0x7a, 0xe2, 0x8a, 0xc1, 0x1a,
}

type edgeCasesIrpcService struct {
	impl edgeCases
}

func newEdgeCasesIrpcService(impl edgeCases) *edgeCasesIrpcService {
	return &edgeCasesIrpcService{
		impl: impl,
	}
}
func (s *edgeCasesIrpcService) Id() []byte {
	return _edgeCasesIrpcId
}
func (s *edgeCasesIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // noReturn
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_noReturnReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.noReturn(args.i)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 1: // noParams
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_edgeCases_noParamsResp
				resp.p0 = s.impl.noParams()
				return resp
			}, nil
		}, nil
	case 2: // nothingAtAll
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.nothingAtAll()
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 3: // unnamedIntParam
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_unnamedIntParamReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.unnamedIntParam(args.p0, args.p1)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 4: // mixedParamIds
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_mixedParamIdsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.mixedParamIds(args.p02, args.p0, args.p2)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 5: // underscoreParamNames
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_underscoreParamNamesReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_edgeCases_underscoreParamNamesResp
				resp.p03 = s.impl.underscoreParamNames(args.p02, args.p0, args.p2)
				return resp
			}, nil
		}, nil
	case 6: // underscoreRtnName
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_underscoreRtnNameReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_edgeCases_underscoreRtnNameResp
				resp.p02, resp.p1 = s.impl.underscoreRtnName(args.p0)
				return resp
			}, nil
		}, nil
	case 7: // paramNamedAsReceiver
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_paramNamedAsReceiverReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.paramNamedAsReceiver(args._c)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// edgeCasesIrpcClient implements edgeCases
type edgeCasesIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newEdgeCasesIrpcClient(endpoint irpcgen.Endpoint) (*edgeCasesIrpcClient, error) {
	if err := endpoint.RegisterClient(_edgeCasesIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &edgeCasesIrpcClient{endpoint: endpoint}, nil
}
func (_c *edgeCasesIrpcClient) noReturn(i int) {
	var req = _irpc_edgeCases_noReturnReq{
		i: i,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 0, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

// noParams is function with no params lol. and this is godoc just above it
func (_c *edgeCasesIrpcClient) noParams() int {
	var resp _irpc_edgeCases_noParamsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 1, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *edgeCasesIrpcClient) nothingAtAll() {
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 2, irpcgen.EmptySerializable{}, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) unnamedIntParam(p0 int, p1 int) {
	var req = _irpc_edgeCases_unnamedIntParamReq{
		p0: p0,
		p1: p1,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 3, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) mixedParamIds(p02 int, p0 uint8, p2 struct{ a int }) {
	var req = _irpc_edgeCases_mixedParamIdsReq{
		p02: p02,
		p0:  p0,
		p2:  p2,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 4, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) underscoreParamNames(p02 int, p0 uint8, p2 float64) (_ float64) {
	var req = _irpc_edgeCases_underscoreParamNamesReq{
		p02: p02,
		p0:  p0,
		p2:  p2,
	}
	var resp _irpc_edgeCases_underscoreParamNamesResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p03
}
func (_c *edgeCasesIrpcClient) underscoreRtnName(p0 int) (_ int, _ uint8) {
	var req = _irpc_edgeCases_underscoreRtnNameReq{
		p0: p0,
	}
	var resp _irpc_edgeCases_underscoreRtnNameResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 6, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p02, resp.p1
}
func (_c2 *edgeCasesIrpcClient) paramNamedAsReceiver(_c int) {
	var req = _irpc_edgeCases_paramNamedAsReceiverReq{
		_c: _c,
	}
	if err := _c2.endpoint.CallRemoteFunc(context.Background(), _edgeCasesIrpcId, 7, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

type _irpc_edgeCases_noReturnReq struct {
	i int
}

func (s _irpc_edgeCases_noReturnReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.i); err != nil {
		return fmt.Errorf("serialize \"i\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_noReturnReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.i); err != nil {
		return fmt.Errorf("deserialize i of type int: %w", err)
	}
	return nil
}

type _irpc_edgeCases_noParamsResp struct {
	p0 int
}

func (s _irpc_edgeCases_noParamsResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_noParamsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}

type _irpc_edgeCases_unnamedIntParamReq struct {
	p0 int
	p1 int
}

func (s _irpc_edgeCases_unnamedIntParamReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize \"p0\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.p1); err != nil {
		return fmt.Errorf("serialize \"p1\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_unnamedIntParamReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize p0 of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize p1 of type int: %w", err)
	}
	return nil
}

type _irpc_edgeCases_mixedParamIdsReq struct {
	p02 int
	p0  uint8
	p2  struct{ a int }
}

func (s _irpc_edgeCases_mixedParamIdsReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p02); err != nil {
		return fmt.Errorf("serialize \"p02\" of type int: %w", err)
	}
	if err := irpcgen.EncUint8(e, s.p0); err != nil {
		return fmt.Errorf("serialize \"p0\" of type uint8: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, s struct{ a int }) error {
		if err := irpcgen.EncInt(enc, s.a); err != nil {
			return fmt.Errorf("serialize s.a of type int: %w", err)
		}
		return nil
	}(e, s.p2); err != nil {
		return fmt.Errorf("serialize \"p2\" of type struct{a int;}: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_mixedParamIdsReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p02); err != nil {
		return fmt.Errorf("deserialize p02 of type int: %w", err)
	}
	if err := irpcgen.DecUint8(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize p0 of type uint8: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *struct{ a int }) error {
		if err := irpcgen.DecInt(dec, &s.a); err != nil {
			return fmt.Errorf("deserialize s.a of type int: %w", err)
		}
		return nil
	}(d, &s.p2); err != nil {
		return fmt.Errorf("deserialize p2 of type struct{a int;}: %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreParamNamesReq struct {
	p02 int
	p0  uint8
	p2  float64
}

func (s _irpc_edgeCases_underscoreParamNamesReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p02); err != nil {
		return fmt.Errorf("serialize \"p02\" of type int: %w", err)
	}
	if err := irpcgen.EncUint8(e, s.p0); err != nil {
		return fmt.Errorf("serialize \"p0\" of type uint8: %w", err)
	}
	if err := irpcgen.EncFloat64(e, s.p2); err != nil {
		return fmt.Errorf("serialize \"p2\" of type float64: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreParamNamesReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p02); err != nil {
		return fmt.Errorf("deserialize p02 of type int: %w", err)
	}
	if err := irpcgen.DecUint8(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize p0 of type uint8: %w", err)
	}
	if err := irpcgen.DecFloat64(d, &s.p2); err != nil {
		return fmt.Errorf("deserialize p2 of type float64: %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreParamNamesResp struct {
	p03 float64
}

func (s _irpc_edgeCases_underscoreParamNamesResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncFloat64(e, s.p03); err != nil {
		return fmt.Errorf("serialize \"_\" of type float64: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreParamNamesResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecFloat64(d, &s.p03); err != nil {
		return fmt.Errorf("deserialize _ of type float64: %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreRtnNameReq struct {
	p0 int
}

func (s _irpc_edgeCases_underscoreRtnNameReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize \"p0\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreRtnNameReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize p0 of type int: %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreRtnNameResp struct {
	p02 int
	p1  uint8
}

func (s _irpc_edgeCases_underscoreRtnNameResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p02); err != nil {
		return fmt.Errorf("serialize \"_\" of type int: %w", err)
	}
	if err := irpcgen.EncUint8(e, s.p1); err != nil {
		return fmt.Errorf("serialize \"_\" of type uint8: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreRtnNameResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p02); err != nil {
		return fmt.Errorf("deserialize _ of type int: %w", err)
	}
	if err := irpcgen.DecUint8(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize _ of type uint8: %w", err)
	}
	return nil
}

type _irpc_edgeCases_paramNamedAsReceiverReq struct {
	_c int
}

func (s _irpc_edgeCases_paramNamedAsReceiverReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s._c); err != nil {
		return fmt.Errorf("serialize \"_c\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_paramNamedAsReceiverReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s._c); err != nil {
		return fmt.Errorf("deserialize _c of type int: %w", err)
	}
	return nil
}

var _anotherInterfaceIrpcId = []byte{
	0x62, 0xbf, 0xfb, 0x5b, 0x1b, 0x0b, 0xa4, 0xde,
	0xee, 0x46, 0xbe, 0xa3, 0x43, 0xc4, 0xa6, 0x4f,
	0x5a, 0x59, 0x7f, 0xee, 0xdc, 0x74, 0x60, 0xd1,
	0x3f, 0x20, 0x74, 0x41, 0x76, 0x9c, 0x85, 0xc7,
}

type anotherInterfaceIrpcService struct {
	impl anotherInterface
}

func newAnotherInterfaceIrpcService(impl anotherInterface) *anotherInterfaceIrpcService {
	return &anotherInterfaceIrpcService{
		impl: impl,
	}
}
func (s *anotherInterfaceIrpcService) Id() []byte {
	return _anotherInterfaceIrpcId
}
func (s *anotherInterfaceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // anotherAdd
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_anotherInterface_anotherAddReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_anotherInterface_anotherAddResp
				resp.p0 = s.impl.anotherAdd(args.a, args.b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// anotherInterfaceIrpcClient implements anotherInterface
type anotherInterfaceIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newAnotherInterfaceIrpcClient(endpoint irpcgen.Endpoint) (*anotherInterfaceIrpcClient, error) {
	if err := endpoint.RegisterClient(_anotherInterfaceIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &anotherInterfaceIrpcClient{endpoint: endpoint}, nil
}
func (_c *anotherInterfaceIrpcClient) anotherAdd(a int, b int) int {
	var req = _irpc_anotherInterface_anotherAddReq{
		a: a,
		b: b,
	}
	var resp _irpc_anotherInterface_anotherAddResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _anotherInterfaceIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_anotherInterface_anotherAddReq struct {
	a int
	b int
}

func (s _irpc_anotherInterface_anotherAddReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_anotherInterface_anotherAddReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type int: %w", err)
	}
	return nil
}

type _irpc_anotherInterface_anotherAddResp struct {
	p0 int
}

func (s _irpc_anotherInterface_anotherAddResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_anotherInterface_anotherAddResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}
