// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type emptyAPIIrpcService struct {
	impl emptyAPI
	id   []byte
}

func newEmptyAPIIrpcService(impl emptyAPI) *emptyAPIIrpcService {
	return &emptyAPIIrpcService{
		impl: impl,
		id: []byte{
			0x7b, 0x34, 0xf2, 0xac, 0xee, 0x77, 0x35, 0x9f,
			0x04, 0x18, 0x60, 0xfc, 0xe9, 0x8c, 0x9b, 0xe4,
			0x4c, 0xd3, 0xcd, 0xf8, 0x8e, 0x02, 0x37, 0xd7,
			0x6d, 0xb0, 0x11, 0x10, 0xbb, 0x6d, 0x5a, 0x1a,
		},
	}
}
func (s *emptyAPIIrpcService) Id() []byte {
	return s.id
}
func (s *emptyAPIIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// emptyAPIIrpcClient implements emptyAPI
type emptyAPIIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newEmptyAPIIrpcClient(endpoint irpcgen.Endpoint) (*emptyAPIIrpcClient, error) {
	id := []byte{
		0x7b, 0x34, 0xf2, 0xac, 0xee, 0x77, 0x35, 0x9f,
		0x04, 0x18, 0x60, 0xfc, 0xe9, 0x8c, 0x9b, 0xe4,
		0x4c, 0xd3, 0xcd, 0xf8, 0x8e, 0x02, 0x37, 0xd7,
		0x6d, 0xb0, 0x11, 0x10, 0xbb, 0x6d, 0x5a, 0x1a,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &emptyAPIIrpcClient{endpoint: endpoint, id: id}, nil
}

type edgeCasesIrpcService struct {
	impl edgeCases
	id   []byte
}

func newEdgeCasesIrpcService(impl edgeCases) *edgeCasesIrpcService {
	return &edgeCasesIrpcService{
		impl: impl,
		id: []byte{
			0x39, 0x3a, 0x40, 0x8d, 0x16, 0xa6, 0x18, 0x9c,
			0xbd, 0x88, 0xbd, 0x70, 0x72, 0x25, 0xc4, 0x5a,
			0x63, 0x00, 0xf7, 0xf7, 0xa7, 0x35, 0x06, 0x6d,
			0x77, 0x69, 0xb4, 0x32, 0xf9, 0x2d, 0xd2, 0x97,
		},
	}
}
func (s *edgeCasesIrpcService) Id() []byte {
	return s.id
}
func (s *edgeCasesIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // noReturn
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_edgeCasesnoReturnReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.noReturn(args.Param0_i)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 1: // noParams
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _Irpc_edgeCasesnoParamsResp
				resp.Param0 = s.impl.noParams()
				return resp
			}, nil
		}, nil
	case 2: // nothingAtAll
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.nothingAtAll()
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 3: // unnamedIntParam
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_edgeCasesunnamedIntParamReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.unnamedIntParam(args.Param0_p0)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 4: // mixedParamIds
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_edgeCasesmixedParamIdsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.mixedParamIds(args.Param0_p0_, args.Param1_p0, args.Param2_p2)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// edgeCasesIrpcClient implements edgeCases
type edgeCasesIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newEdgeCasesIrpcClient(endpoint irpcgen.Endpoint) (*edgeCasesIrpcClient, error) {
	id := []byte{
		0x39, 0x3a, 0x40, 0x8d, 0x16, 0xa6, 0x18, 0x9c,
		0xbd, 0x88, 0xbd, 0x70, 0x72, 0x25, 0xc4, 0x5a,
		0x63, 0x00, 0xf7, 0xf7, 0xa7, 0x35, 0x06, 0x6d,
		0x77, 0x69, 0xb4, 0x32, 0xf9, 0x2d, 0xd2, 0x97,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &edgeCasesIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *edgeCasesIrpcClient) noReturn(i int) {
	var req = _Irpc_edgeCasesnoReturnReq{
		Param0_i: i,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) noParams() int {
	var resp _Irpc_edgeCasesnoParamsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 1, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.Param0
}
func (_c *edgeCasesIrpcClient) nothingAtAll() {
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 2, irpcgen.EmptySerializable{}, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) unnamedIntParam(p0 int) {
	var req = _Irpc_edgeCasesunnamedIntParamReq{
		Param0_p0: p0,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 3, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) mixedParamIds(p0_ int, p0 uint8, p2 struct{ a int }) {
	var req = _Irpc_edgeCasesmixedParamIdsReq{
		Param0_p0_: p0_,
		Param1_p0:  p0,
		Param2_p2:  p2,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 4, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

type _Irpc_edgeCasesnoReturnReq struct {
	Param0_i int
}

func (s _Irpc_edgeCasesnoReturnReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0_i); err != nil {
		return fmt.Errorf("serialize s.Param0_i of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_edgeCasesnoReturnReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0_i); err != nil {
		return fmt.Errorf("deserialize s.Param0_i of type \"int\": %w", err)
	}
	return nil
}

type _Irpc_edgeCasesnoParamsResp struct {
	Param0 int
}

func (s _Irpc_edgeCasesnoParamsResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0); err != nil {
		return fmt.Errorf("serialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_edgeCasesnoParamsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0); err != nil {
		return fmt.Errorf("deserialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}

type _Irpc_edgeCasesunnamedIntParamReq struct {
	Param0_p0 int
}

func (s _Irpc_edgeCasesunnamedIntParamReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0_p0); err != nil {
		return fmt.Errorf("serialize s.Param0_p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_edgeCasesunnamedIntParamReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0_p0); err != nil {
		return fmt.Errorf("deserialize s.Param0_p0 of type \"int\": %w", err)
	}
	return nil
}

type _Irpc_edgeCasesmixedParamIdsReq struct {
	Param0_p0_ int
	Param1_p0  uint8
	Param2_p2  struct{ a int }
}

func (s _Irpc_edgeCasesmixedParamIdsReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0_p0_); err != nil {
		return fmt.Errorf("serialize s.Param0_p0_ of type \"int\": %w", err)
	}
	if err := e.Uint8(s.Param1_p0); err != nil {
		return fmt.Errorf("serialize s.Param1_p0 of type \"uint8\": %w", err)
	}
	if err := e.VarInt(s.Param2_p2.a); err != nil {
		return fmt.Errorf("serialize s.Param2_p2.a of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_edgeCasesmixedParamIdsReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0_p0_); err != nil {
		return fmt.Errorf("deserialize s.Param0_p0_ of type \"int\": %w", err)
	}
	if err := d.Uint8(&s.Param1_p0); err != nil {
		return fmt.Errorf("deserialize s.Param1_p0 of type \"uint8\": %w", err)
	}
	if err := d.VarInt(&s.Param2_p2.a); err != nil {
		return fmt.Errorf("deserialize s.Param2_p2.a of type \"int\": %w", err)
	}
	return nil
}

type anotherInterfaceIrpcService struct {
	impl anotherInterface
	id   []byte
}

func newAnotherInterfaceIrpcService(impl anotherInterface) *anotherInterfaceIrpcService {
	return &anotherInterfaceIrpcService{
		impl: impl,
		id: []byte{
			0xb3, 0x76, 0xe4, 0x83, 0x80, 0x4c, 0x8a, 0xeb,
			0x1e, 0xe1, 0x7a, 0x98, 0x13, 0x44, 0xea, 0x8b,
			0xa5, 0xea, 0xda, 0x0a, 0xc4, 0xc3, 0xaf, 0xdf,
			0x67, 0x75, 0x9b, 0x76, 0xc4, 0x16, 0x96, 0x06,
		},
	}
}
func (s *anotherInterfaceIrpcService) Id() []byte {
	return s.id
}
func (s *anotherInterfaceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // anotherAdd
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_anotherInterfaceanotherAddReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _Irpc_anotherInterfaceanotherAddResp
				resp.Param0 = s.impl.anotherAdd(args.Param0_a, args.Param0_b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// anotherInterfaceIrpcClient implements anotherInterface
type anotherInterfaceIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newAnotherInterfaceIrpcClient(endpoint irpcgen.Endpoint) (*anotherInterfaceIrpcClient, error) {
	id := []byte{
		0xb3, 0x76, 0xe4, 0x83, 0x80, 0x4c, 0x8a, 0xeb,
		0x1e, 0xe1, 0x7a, 0x98, 0x13, 0x44, 0xea, 0x8b,
		0xa5, 0xea, 0xda, 0x0a, 0xc4, 0xc3, 0xaf, 0xdf,
		0x67, 0x75, 0x9b, 0x76, 0xc4, 0x16, 0x96, 0x06,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &anotherInterfaceIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *anotherInterfaceIrpcClient) anotherAdd(a int, b int) int {
	var req = _Irpc_anotherInterfaceanotherAddReq{
		Param0_a: a,
		Param0_b: b,
	}
	var resp _Irpc_anotherInterfaceanotherAddResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.Param0
}

type _Irpc_anotherInterfaceanotherAddReq struct {
	Param0_a int
	Param0_b int
}

func (s _Irpc_anotherInterfaceanotherAddReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0_a); err != nil {
		return fmt.Errorf("serialize s.Param0_a of type \"int\": %w", err)
	}
	if err := e.VarInt(s.Param0_b); err != nil {
		return fmt.Errorf("serialize s.Param0_b of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_anotherInterfaceanotherAddReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0_a); err != nil {
		return fmt.Errorf("deserialize s.Param0_a of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.Param0_b); err != nil {
		return fmt.Errorf("deserialize s.Param0_b of type \"int\": %w", err)
	}
	return nil
}

type _Irpc_anotherInterfaceanotherAddResp struct {
	Param0 int
}

func (s _Irpc_anotherInterfaceanotherAddResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0); err != nil {
		return fmt.Errorf("serialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_anotherInterfaceanotherAddResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0); err != nil {
		return fmt.Errorf("deserialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}
