// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/edgecases.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type emptyAPIIrpcService struct {
	impl emptyAPI
	id   []byte
}

func newEmptyAPIIrpcService(impl emptyAPI) *emptyAPIIrpcService {
	return &emptyAPIIrpcService{
		impl: impl,
		id: []byte{
			0x04, 0x73, 0x69, 0xb5, 0x72, 0x7f, 0x93, 0x57,
			0xb0, 0x7c, 0x49, 0x20, 0x73, 0x8f, 0xe8, 0xf2,
			0xb8, 0xc4, 0x3d, 0xc9, 0x9e, 0x29, 0x3a, 0xa5,
			0x14, 0x67, 0x36, 0xfa, 0xca, 0x87, 0x51, 0xc8,
		},
	}
}
func (s *emptyAPIIrpcService) Id() []byte {
	return s.id
}
func (s *emptyAPIIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// emptyAPIIrpcClient implements emptyAPI
type emptyAPIIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newEmptyAPIIrpcClient(endpoint irpcgen.Endpoint) (*emptyAPIIrpcClient, error) {
	id := []byte{
		0x04, 0x73, 0x69, 0xb5, 0x72, 0x7f, 0x93, 0x57,
		0xb0, 0x7c, 0x49, 0x20, 0x73, 0x8f, 0xe8, 0xf2,
		0xb8, 0xc4, 0x3d, 0xc9, 0x9e, 0x29, 0x3a, 0xa5,
		0x14, 0x67, 0x36, 0xfa, 0xca, 0x87, 0x51, 0xc8,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &emptyAPIIrpcClient{endpoint: endpoint, id: id}, nil
}

type edgeCasesIrpcService struct {
	impl edgeCases
	id   []byte
}

func newEdgeCasesIrpcService(impl edgeCases) *edgeCasesIrpcService {
	return &edgeCasesIrpcService{
		impl: impl,
		id: []byte{
			0xbb, 0x02, 0x86, 0x75, 0xdf, 0x9e, 0xb5, 0x1d,
			0xe0, 0x09, 0x29, 0x20, 0x1d, 0xc6, 0xdd, 0x24,
			0x1c, 0x9d, 0x84, 0x5a, 0x48, 0x6f, 0xb2, 0x30,
			0x63, 0xf7, 0xd7, 0x3b, 0x20, 0xa5, 0xa3, 0x47,
		},
	}
}
func (s *edgeCasesIrpcService) Id() []byte {
	return s.id
}
func (s *edgeCasesIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // noReturn
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_noReturnReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.noReturn(args.i)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 1: // noParams
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_edgeCases_noParamsResp
				resp.p0 = s.impl.noParams()
				return resp
			}, nil
		}, nil
	case 2: // nothingAtAll
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.nothingAtAll()
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 3: // unnamedIntParam
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_unnamedIntParamReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.unnamedIntParam(args.p0, args.p1)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 4: // mixedParamIds
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_mixedParamIdsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.mixedParamIds(args.p02, args.p0, args.p2)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 5: // underscoreParamNames
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_underscoreParamNamesReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_edgeCases_underscoreParamNamesResp
				resp.p03 = s.impl.underscoreParamNames(args.p02, args.p0, args.p2)
				return resp
			}, nil
		}, nil
	case 6: // underscoreRtnName
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_underscoreRtnNameReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_edgeCases_underscoreRtnNameResp
				resp.p02, resp.p1 = s.impl.underscoreRtnName(args.p0)
				return resp
			}, nil
		}, nil
	case 7: // paramNamedAsReceiver
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_edgeCases_paramNamedAsReceiverReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.paramNamedAsReceiver(args._c)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// edgeCasesIrpcClient implements edgeCases
type edgeCasesIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newEdgeCasesIrpcClient(endpoint irpcgen.Endpoint) (*edgeCasesIrpcClient, error) {
	id := []byte{
		0xbb, 0x02, 0x86, 0x75, 0xdf, 0x9e, 0xb5, 0x1d,
		0xe0, 0x09, 0x29, 0x20, 0x1d, 0xc6, 0xdd, 0x24,
		0x1c, 0x9d, 0x84, 0x5a, 0x48, 0x6f, 0xb2, 0x30,
		0x63, 0xf7, 0xd7, 0x3b, 0x20, 0xa5, 0xa3, 0x47,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &edgeCasesIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *edgeCasesIrpcClient) noReturn(i int) {
	var req = _irpc_edgeCases_noReturnReq{
		i: i,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

// noParams is function with no params lol. and this is godoc just above it
func (_c *edgeCasesIrpcClient) noParams() int {
	var resp _irpc_edgeCases_noParamsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 1, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *edgeCasesIrpcClient) nothingAtAll() {
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 2, irpcgen.EmptySerializable{}, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) unnamedIntParam(p0 int, p1 int) {
	var req = _irpc_edgeCases_unnamedIntParamReq{
		p0: p0,
		p1: p1,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 3, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) mixedParamIds(p02 int, p0 uint8, p2 struct{ a int }) {
	var req = _irpc_edgeCases_mixedParamIdsReq{
		p02: p02,
		p0:  p0,
		p2:  p2,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 4, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}
func (_c *edgeCasesIrpcClient) underscoreParamNames(p02 int, p0 uint8, p2 float64) (_ float64) {
	var req = _irpc_edgeCases_underscoreParamNamesReq{
		p02: p02,
		p0:  p0,
		p2:  p2,
	}
	var resp _irpc_edgeCases_underscoreParamNamesResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p03
}
func (_c *edgeCasesIrpcClient) underscoreRtnName(p0 int) (_ int, _ uint8) {
	var req = _irpc_edgeCases_underscoreRtnNameReq{
		p0: p0,
	}
	var resp _irpc_edgeCases_underscoreRtnNameResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 6, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p02, resp.p1
}
func (_c2 *edgeCasesIrpcClient) paramNamedAsReceiver(_c int) {
	var req = _irpc_edgeCases_paramNamedAsReceiverReq{
		_c: _c,
	}
	if err := _c2.endpoint.CallRemoteFunc(context.Background(), _c2.id, 7, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

type _irpc_edgeCases_noReturnReq struct {
	i int
}

func (s _irpc_edgeCases_noReturnReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.i); err != nil {
		return fmt.Errorf("serialize s.i of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_noReturnReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.i); err != nil {
		return fmt.Errorf("deserialize s.i of type \"int\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_noParamsResp struct {
	p0 int
}

func (s _irpc_edgeCases_noParamsResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_noParamsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_unnamedIntParamReq struct {
	p0 int
	p1 int
}

func (s _irpc_edgeCases_unnamedIntParamReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	if err := e.VarInt(s.p1); err != nil {
		return fmt.Errorf("serialize s.p1 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_unnamedIntParamReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.p1); err != nil {
		return fmt.Errorf("deserialize s.p1 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_mixedParamIdsReq struct {
	p02 int
	p0  uint8
	p2  struct{ a int }
}

func (s _irpc_edgeCases_mixedParamIdsReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p02); err != nil {
		return fmt.Errorf("serialize s.p02 of type \"int\": %w", err)
	}
	if err := e.Uint8(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"uint8\": %w", err)
	}
	if err := e.VarInt(s.p2.a); err != nil {
		return fmt.Errorf("serialize s.p2.a of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_mixedParamIdsReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p02); err != nil {
		return fmt.Errorf("deserialize s.p02 of type \"int\": %w", err)
	}
	if err := d.Uint8(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"uint8\": %w", err)
	}
	if err := d.VarInt(&s.p2.a); err != nil {
		return fmt.Errorf("deserialize s.p2.a of type \"int\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreParamNamesReq struct {
	p02 int
	p0  uint8
	p2  float64
}

func (s _irpc_edgeCases_underscoreParamNamesReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p02); err != nil {
		return fmt.Errorf("serialize s.p02 of type \"int\": %w", err)
	}
	if err := e.Uint8(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"uint8\": %w", err)
	}
	if err := e.Float64le(s.p2); err != nil {
		return fmt.Errorf("serialize s.p2 of type \"float64\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreParamNamesReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p02); err != nil {
		return fmt.Errorf("deserialize s.p02 of type \"int\": %w", err)
	}
	if err := d.Uint8(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"uint8\": %w", err)
	}
	if err := d.Float64le(&s.p2); err != nil {
		return fmt.Errorf("deserialize s.p2 of type \"float64\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreParamNamesResp struct {
	p03 float64
}

func (s _irpc_edgeCases_underscoreParamNamesResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(s.p03); err != nil {
		return fmt.Errorf("serialize s.p03 of type \"float64\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreParamNamesResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le(&s.p03); err != nil {
		return fmt.Errorf("deserialize s.p03 of type \"float64\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreRtnNameReq struct {
	p0 int
}

func (s _irpc_edgeCases_underscoreRtnNameReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreRtnNameReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_underscoreRtnNameResp struct {
	p02 int
	p1  uint8
}

func (s _irpc_edgeCases_underscoreRtnNameResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p02); err != nil {
		return fmt.Errorf("serialize s.p02 of type \"int\": %w", err)
	}
	if err := e.Uint8(s.p1); err != nil {
		return fmt.Errorf("serialize s.p1 of type \"uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_underscoreRtnNameResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p02); err != nil {
		return fmt.Errorf("deserialize s.p02 of type \"int\": %w", err)
	}
	if err := d.Uint8(&s.p1); err != nil {
		return fmt.Errorf("deserialize s.p1 of type \"uint8\": %w", err)
	}
	return nil
}

type _irpc_edgeCases_paramNamedAsReceiverReq struct {
	_c int
}

func (s _irpc_edgeCases_paramNamedAsReceiverReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s._c); err != nil {
		return fmt.Errorf("serialize s._c of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_edgeCases_paramNamedAsReceiverReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s._c); err != nil {
		return fmt.Errorf("deserialize s._c of type \"int\": %w", err)
	}
	return nil
}

type anotherInterfaceIrpcService struct {
	impl anotherInterface
	id   []byte
}

func newAnotherInterfaceIrpcService(impl anotherInterface) *anotherInterfaceIrpcService {
	return &anotherInterfaceIrpcService{
		impl: impl,
		id: []byte{
			0x5a, 0x44, 0xc3, 0xd5, 0x9e, 0x2f, 0xca, 0x5e,
			0x0a, 0x6d, 0xca, 0x1e, 0xbd, 0xc3, 0xc4, 0xbd,
			0x27, 0x61, 0x5e, 0xeb, 0x9e, 0x21, 0x03, 0xe7,
			0xa0, 0x6c, 0xda, 0x55, 0xad, 0x92, 0xcc, 0x65,
		},
	}
}
func (s *anotherInterfaceIrpcService) Id() []byte {
	return s.id
}
func (s *anotherInterfaceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // anotherAdd
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_anotherInterface_anotherAddReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_anotherInterface_anotherAddResp
				resp.p0 = s.impl.anotherAdd(args.a, args.b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// anotherInterfaceIrpcClient implements anotherInterface
type anotherInterfaceIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newAnotherInterfaceIrpcClient(endpoint irpcgen.Endpoint) (*anotherInterfaceIrpcClient, error) {
	id := []byte{
		0x5a, 0x44, 0xc3, 0xd5, 0x9e, 0x2f, 0xca, 0x5e,
		0x0a, 0x6d, 0xca, 0x1e, 0xbd, 0xc3, 0xc4, 0xbd,
		0x27, 0x61, 0x5e, 0xeb, 0x9e, 0x21, 0x03, 0xe7,
		0xa0, 0x6c, 0xda, 0x55, 0xad, 0x92, 0xcc, 0x65,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &anotherInterfaceIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *anotherInterfaceIrpcClient) anotherAdd(a int, b int) int {
	var req = _irpc_anotherInterface_anotherAddReq{
		a: a,
		b: b,
	}
	var resp _irpc_anotherInterface_anotherAddResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_anotherInterface_anotherAddReq struct {
	a int
	b int
}

func (s _irpc_anotherInterface_anotherAddReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int\": %w", err)
	}
	if err := e.VarInt(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_anotherInterface_anotherAddReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int\": %w", err)
	}
	return nil
}

type _irpc_anotherInterface_anotherAddResp struct {
	p0 int
}

func (s _irpc_anotherInterface_anotherAddResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_anotherInterface_anotherAddResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
