// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/emptyinterface.go
package irpctestpkg

import (
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type emptyInterfaceIrpcService struct {
	impl emptyInterface
	id   []byte
}

func newEmptyInterfaceIrpcService(impl emptyInterface) *emptyInterfaceIrpcService {
	return &emptyInterfaceIrpcService{
		impl: impl,
		id: []byte{
			0x82, 0x7e, 0x0b, 0x3c, 0x11, 0xd3, 0x18, 0xff,
			0x1f, 0x5d, 0xa5, 0x73, 0x0c, 0xce, 0x85, 0x15,
			0x80, 0xc6, 0xbd, 0xfe, 0xd6, 0xc8, 0x24, 0x32,
			0x9c, 0x92, 0xba, 0xda, 0x79, 0x1a, 0x75, 0xb0,
		},
	}
}
func (s *emptyInterfaceIrpcService) Id() []byte {
	return s.id
}
func (s *emptyInterfaceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// emptyInterfaceIrpcClient implements emptyInterface
type emptyInterfaceIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newEmptyInterfaceIrpcClient(endpoint irpcgen.Endpoint) (*emptyInterfaceIrpcClient, error) {
	id := []byte{
		0x82, 0x7e, 0x0b, 0x3c, 0x11, 0xd3, 0x18, 0xff,
		0x1f, 0x5d, 0xa5, 0x73, 0x0c, 0xce, 0x85, 0x15,
		0x80, 0xc6, 0xbd, 0xfe, 0xd6, 0xc8, 0x24, 0x32,
		0x9c, 0x92, 0xba, 0xda, 0x79, 0x1a, 0x75, 0xb0,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &emptyInterfaceIrpcClient{endpoint: endpoint, id: id}, nil
}
