// Code generated by irpc (devel); DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/emptyinterface.go
package irpctestpkg

import (
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _emptyInterfaceIrpcId = irpcgen.ServiceId(0xbb053051a09ca313)

// emptyInterfaceIrpcService provides [emptyInterface] interface over irpc
type emptyInterfaceIrpcService struct {
	impl emptyInterface
}

// newEmptyInterfaceIrpcService returns new [irpcgen.Service] forwarding [emptyInterface] network calls to impl
func newEmptyInterfaceIrpcService(impl emptyInterface) *emptyInterfaceIrpcService {
	return &emptyInterfaceIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *emptyInterfaceIrpcService) Id() irpcgen.ServiceId {
	return _emptyInterfaceIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *emptyInterfaceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// emptyInterfaceIrpcClient implements [emptyInterface] interface. It by forwards calls over network to [emptyInterfaceIrpcService] that provides the implementation.
type emptyInterfaceIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newEmptyInterfaceIrpcClient(endpoint irpcgen.Endpoint) (*emptyInterfaceIrpcClient, error) {
	if err := endpoint.RegisterClient(_emptyInterfaceIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &emptyInterfaceIrpcClient{endpoint: endpoint}, nil
}
