// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type emptyInterfaceIRpcService struct {
	impl emptyInterface
	id   []byte
}

func newEmptyInterfaceIRpcService(impl emptyInterface) *emptyInterfaceIRpcService {
	return &emptyInterfaceIRpcService{
		impl: impl,
		id:   []byte{88, 205, 147, 100, 223, 27, 125, 78, 4, 123, 34, 85, 40, 224, 68, 165, 248, 253, 244, 113, 20, 197, 229, 158, 74, 131, 141, 194, 136, 220, 225, 58},
	}
}
func (s *emptyInterfaceIRpcService) Id() []byte {
	return s.id
}
func (s *emptyInterfaceIRpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

type emptyInterfaceIRpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newEmptyInterfaceIRpcClient(endpoint irpcgen.Endpoint) (*emptyInterfaceIRpcClient, error) {
	id := []byte{88, 205, 147, 100, 223, 27, 125, 78, 4, 123, 34, 85, 40, 224, 68, 165, 248, 253, 244, 113, 20, 197, 229, 158, 74, 131, 141, 194, 136, 220, 225, 58}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &emptyInterfaceIRpcClient{endpoint: endpoint, id: id}, nil
}
