// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type FileServerIrpcService struct {
	impl FileServer
	id   []byte
}

func NewFileServerIrpcService(impl FileServer) *FileServerIrpcService {
	return &FileServerIrpcService{
		impl: impl,
		id: []byte{
			0xe5, 0x80, 0x23, 0x0b, 0xac, 0x15, 0x0d, 0xc7,
			0x37, 0x69, 0xe8, 0x58, 0x5f, 0x4e, 0x89, 0x8b,
			0xdf, 0x31, 0x95, 0x1f, 0xad, 0x26, 0x1b, 0x94,
			0x86, 0xad, 0x7d, 0x62, 0x48, 0xbd, 0x42, 0x95,
		},
	}
}
func (s *FileServerIrpcService) Id() []byte {
	return s.id
}
func (s *FileServerIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // ListFiles
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_FileServer_ListFilesResp
				resp.Param0, resp.Param1 = s.impl.ListFiles()
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// FileServerIrpcClient implements FileServer
type FileServerIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func NewFileServerIrpcClient(endpoint irpcgen.Endpoint) (*FileServerIrpcClient, error) {
	id := []byte{
		0xe5, 0x80, 0x23, 0x0b, 0xac, 0x15, 0x0d, 0xc7,
		0x37, 0x69, 0xe8, 0x58, 0x5f, 0x4e, 0x89, 0x8b,
		0xdf, 0x31, 0x95, 0x1f, 0xad, 0x26, 0x1b, 0x94,
		0x86, 0xad, 0x7d, 0x62, 0x48, 0xbd, 0x42, 0x95,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &FileServerIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *FileServerIrpcClient) ListFiles() ([]FileInfo, error) {
	var resp _irpc_FileServer_ListFilesResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, irpcgen.EmptySerializable{}, &resp); err != nil {
		var zero _irpc_FileServer_ListFilesResp
		return zero.Param0, err
	}
	return resp.Param0, resp.Param1
}

type _irpc_FileServer_ListFilesResp struct {
	Param0 []FileInfo
	Param1 error
}

func (s _irpc_FileServer_ListFilesResp) Serialize(e *irpcgen.Encoder) error {
	{ // s.Param0 []FileInfo
		if err := e.Len(len(s.Param0)); err != nil {
			return fmt.Errorf("serialize len(s.Param0) of type \"int\": %w", err)
		}
		for _, v := range s.Param0 {
			if err := e.UvarInt64(v.FileSize); err != nil {
				return fmt.Errorf("serialize v.FileSize of type \"uint64\": %w", err)
			}
		}
	}
	{
		var isNil bool
		if s.Param1 == nil {
			isNil = true
		}
		if err := e.Bool(isNil); err != nil {
			return fmt.Errorf("serialize isNil of type \"bool\": %w", err)
		}

		if !isNil {
			{ // Error()
				_Error_0_ := s.Param1.Error()
				if err := e.String(_Error_0_); err != nil {
					return fmt.Errorf("serialize _Error_0_ of type \"string\": %w", err)
				}
			}
		}
	}
	return nil
}
func (s *_irpc_FileServer_ListFilesResp) Deserialize(d *irpcgen.Decoder) error {
	{ // s.Param0 []FileInfo
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.Param0 = make([]FileInfo, l)
		for i := range l {
			if err := d.UvarInt64(&s.Param0[i].FileSize); err != nil {
				return fmt.Errorf("deserialize s.Param0[i].FileSize of type \"uint64\": %w", err)
			}
		}
	}
	{
		var isNil bool
		if err := d.Bool(&isNil); err != nil {
			return fmt.Errorf("deserialize isNil of type \"bool\": %w", err)
		}

		if isNil {
			s.Param1 = nil
		} else {
			var impl _error_FileServer_impl
			{ // Error()
				if err := d.String(&impl._Error_0_); err != nil {
					return fmt.Errorf("deserialize impl._Error_0_ of type \"string\": %w", err)
				}
			}
			s.Param1 = impl
		}
	}
	return nil
}

type _error_FileServer_impl struct {
	_Error_0_ string
}

func (i _error_FileServer_impl) Error() string {
	return i._Error_0_
}
