// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/interface.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/cmd/irpc/test/out"
	out2 "github.com/marben/irpc/cmd/irpc/test/out"
	"github.com/marben/irpc/irpcgen"
)

var _interfaceTestIrpcId = []byte{
	0xf0, 0x0e, 0x8a, 0xe0, 0x8a, 0xc6, 0x46, 0xb4,
	0xa2, 0xdb, 0x27, 0x90, 0x8e, 0x0d, 0x12, 0x42,
	0x94, 0x6c, 0x36, 0x2b, 0x3e, 0x2a, 0x0d, 0x09,
	0x17, 0xb9, 0xe7, 0x0b, 0x99, 0xe6, 0x14, 0xb3,
}

type interfaceTestIrpcService struct {
	impl interfaceTest
}

func newInterfaceTestIrpcService(impl interfaceTest) *interfaceTestIrpcService {
	return &interfaceTestIrpcService{
		impl: impl,
	}
}
func (s *interfaceTestIrpcService) Id() []byte {
	return _interfaceTestIrpcId
}
func (s *interfaceTestIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // rtnErrorWithMessage
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_interfaceTest_rtnErrorWithMessageReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_rtnErrorWithMessageResp
				resp.p0 = s.impl.rtnErrorWithMessage(args.msg)
				return resp
			}, nil
		}, nil
	case 1: // rtnNilError
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_rtnNilErrorResp
				resp.p0 = s.impl.rtnNilError()
				return resp
			}, nil
		}, nil
	case 2: // rtnTwoErrors
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_rtnTwoErrorsResp
				resp.p0, resp.p1 = s.impl.rtnTwoErrors()
				return resp
			}, nil
		}, nil
	case 3: // rtnStringAndError
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_interfaceTest_rtnStringAndErrorReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_rtnStringAndErrorResp
				resp.s, resp.err = s.impl.rtnStringAndError(args.msg)
				return resp
			}, nil
		}, nil
	case 4: // passCustomInterfaceAndReturnItModified
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedResp
				resp.p0, resp.p1 = s.impl.passCustomInterfaceAndReturnItModified(args.ci)
				return resp
			}, nil
		}, nil
	case 5: // passJustCustomInterfaceWithoutError
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorResp
				resp.p0 = s.impl.passJustCustomInterfaceWithoutError(args.ci)
				return resp
			}, nil
		}, nil
	case 6: // passAnonInterface
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_interfaceTest_passAnonInterfaceReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_passAnonInterfaceResp
				resp.p0 = s.impl.passAnonInterface(args.input)
				return resp
			}, nil
		}, nil
	case 7: // passAnonInterfaceWithNamedParams
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_interfaceTest_passAnonInterfaceWithNamedParamsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_interfaceTest_passAnonInterfaceWithNamedParamsResp
				resp.p0 = s.impl.passAnonInterfaceWithNamedParams(args.input)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// interfaceTestIrpcClient implements interfaceTest
type interfaceTestIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newInterfaceTestIrpcClient(endpoint irpcgen.Endpoint) (*interfaceTestIrpcClient, error) {
	if err := endpoint.RegisterClient(_interfaceTestIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &interfaceTestIrpcClient{endpoint: endpoint}, nil
}
func (_c *interfaceTestIrpcClient) rtnErrorWithMessage(msg string) error {
	var req = _irpc_interfaceTest_rtnErrorWithMessageReq{
		msg: msg,
	}
	var resp _irpc_interfaceTest_rtnErrorWithMessageResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 0, req, &resp); err != nil {
		return err
	}
	return resp.p0
}
func (_c *interfaceTestIrpcClient) rtnNilError() error {
	var resp _irpc_interfaceTest_rtnNilErrorResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 1, irpcgen.EmptySerializable{}, &resp); err != nil {
		return err
	}
	return resp.p0
}
func (_c *interfaceTestIrpcClient) rtnTwoErrors() (error, error) {
	var resp _irpc_interfaceTest_rtnTwoErrorsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 2, irpcgen.EmptySerializable{}, &resp); err != nil {
		var zero _irpc_interfaceTest_rtnTwoErrorsResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}
func (_c *interfaceTestIrpcClient) rtnStringAndError(msg string) (s string, err error) {
	var req = _irpc_interfaceTest_rtnStringAndErrorReq{
		msg: msg,
	}
	var resp _irpc_interfaceTest_rtnStringAndErrorResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 3, req, &resp); err != nil {
		var zero _irpc_interfaceTest_rtnStringAndErrorResp
		return zero.s, err
	}
	return resp.s, resp.err
}
func (_c *interfaceTestIrpcClient) passCustomInterfaceAndReturnItModified(ci customInterface) (customInterface, error) {
	var req = _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedReq{
		ci: ci,
	}
	var resp _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 4, req, &resp); err != nil {
		var zero _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}
func (_c *interfaceTestIrpcClient) passJustCustomInterfaceWithoutError(ci customInterface) customInterface {
	var req = _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorReq{
		ci: ci,
	}
	var resp _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// anonymous interface: // todo: write a test
func (_c *interfaceTestIrpcClient) passAnonInterface(input interface {
	Age() int
	Name() string
}) string {
	var req = _irpc_interfaceTest_passAnonInterfaceReq{
		input: input,
	}
	var resp _irpc_interfaceTest_passAnonInterfaceResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 6, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *interfaceTestIrpcClient) passAnonInterfaceWithNamedParams(input interface {
	a() (out.Uint8, int)
	b() out2.Uint8
	c() (out2.Uint8, error)
}) string {
	var req = _irpc_interfaceTest_passAnonInterfaceWithNamedParamsReq{
		input: input,
	}
	var resp _irpc_interfaceTest_passAnonInterfaceWithNamedParamsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _interfaceTestIrpcId, 7, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_interfaceTest_rtnErrorWithMessageReq struct {
	msg string
}

func (s _irpc_interfaceTest_rtnErrorWithMessageReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.msg); err != nil {
		return fmt.Errorf("serialize \"msg\" of type string: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_rtnErrorWithMessageReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.msg); err != nil {
		return fmt.Errorf("deserialize msg of type string: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_rtnErrorWithMessageResp struct {
	p0 error
}

func (s _irpc_interfaceTest_rtnErrorWithMessageResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_rtnErrorWithMessageResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _error_interfaceTest_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_interfaceTest_impl struct {
	_Error_0_ string
}

func (i _error_interfaceTest_impl) Error() string {
	return i._Error_0_
}

type _irpc_interfaceTest_rtnNilErrorResp struct {
	p0 error
}

func (s _irpc_interfaceTest_rtnNilErrorResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_rtnNilErrorResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _error_interfaceTest_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_rtnTwoErrorsResp struct {
	p0 error
	p1 error
}

func (s _irpc_interfaceTest_rtnTwoErrorsResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_rtnTwoErrorsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _error_interfaceTest_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _error_interfaceTest_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_rtnStringAndErrorReq struct {
	msg string
}

func (s _irpc_interfaceTest_rtnStringAndErrorReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.msg); err != nil {
		return fmt.Errorf("serialize \"msg\" of type string: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_rtnStringAndErrorReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.msg); err != nil {
		return fmt.Errorf("deserialize msg of type string: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_rtnStringAndErrorResp struct {
	s   string
	err error
}

func (s _irpc_interfaceTest_rtnStringAndErrorResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.s); err != nil {
		return fmt.Errorf("serialize \"s\" of type string: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.err); err != nil {
		return fmt.Errorf("serialize \"err\" of type error: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_rtnStringAndErrorResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.s); err != nil {
		return fmt.Errorf("deserialize s of type string: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _error_interfaceTest_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.err); err != nil {
		return fmt.Errorf("deserialize err of type error: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedReq struct {
	ci customInterface
}

func (s _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v customInterface) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_IntFunc_0_ := v.IntFunc()
		if err := irpcgen.EncInt(enc, _IntFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.IntFunc()\" of type int: %w", err)
		}
		_StringFunc_0_ := v.StringFunc()
		if err := irpcgen.EncString(enc, _StringFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.StringFunc()\" of type string: %w", err)
		}
		return nil
	}(e, s.ci); err != nil {
		return fmt.Errorf("serialize \"ci\" of type customInterface: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *customInterface) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _customInterface_interfaceTest_impl
		if err := irpcgen.DecInt(dec, &impl._IntFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_IntFunc_0_\" int: %w", err)
		}
		if err := irpcgen.DecString(dec, &impl._StringFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_StringFunc_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.ci); err != nil {
		return fmt.Errorf("deserialize ci of type customInterface: %w", err)
	}
	return nil
}

type _customInterface_interfaceTest_impl struct {
	_IntFunc_0_    int
	_StringFunc_0_ string
}

func (i _customInterface_interfaceTest_impl) IntFunc() int {
	return i._IntFunc_0_
}
func (i _customInterface_interfaceTest_impl) StringFunc() string {
	return i._StringFunc_0_
}

type _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedResp struct {
	p0 customInterface
	p1 error
}

func (s _irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v customInterface) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_IntFunc_0_ := v.IntFunc()
		if err := irpcgen.EncInt(enc, _IntFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.IntFunc()\" of type int: %w", err)
		}
		_StringFunc_0_ := v.StringFunc()
		if err := irpcgen.EncString(enc, _StringFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.StringFunc()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type customInterface: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passCustomInterfaceAndReturnItModifiedResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *customInterface) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _customInterface_interfaceTest_impl
		if err := irpcgen.DecInt(dec, &impl._IntFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_IntFunc_0_\" int: %w", err)
		}
		if err := irpcgen.DecString(dec, &impl._StringFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_StringFunc_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type customInterface: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _error_interfaceTest_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorReq struct {
	ci customInterface
}

func (s _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v customInterface) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_IntFunc_0_ := v.IntFunc()
		if err := irpcgen.EncInt(enc, _IntFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.IntFunc()\" of type int: %w", err)
		}
		_StringFunc_0_ := v.StringFunc()
		if err := irpcgen.EncString(enc, _StringFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.StringFunc()\" of type string: %w", err)
		}
		return nil
	}(e, s.ci); err != nil {
		return fmt.Errorf("serialize \"ci\" of type customInterface: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passJustCustomInterfaceWithoutErrorReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *customInterface) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _customInterface_interfaceTest_impl
		if err := irpcgen.DecInt(dec, &impl._IntFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_IntFunc_0_\" int: %w", err)
		}
		if err := irpcgen.DecString(dec, &impl._StringFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_StringFunc_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.ci); err != nil {
		return fmt.Errorf("deserialize ci of type customInterface: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorResp struct {
	p0 customInterface
}

func (s _irpc_interfaceTest_passJustCustomInterfaceWithoutErrorResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v customInterface) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_IntFunc_0_ := v.IntFunc()
		if err := irpcgen.EncInt(enc, _IntFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.IntFunc()\" of type int: %w", err)
		}
		_StringFunc_0_ := v.StringFunc()
		if err := irpcgen.EncString(enc, _StringFunc_0_); err != nil {
			return fmt.Errorf("serialize \"v.StringFunc()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type customInterface: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passJustCustomInterfaceWithoutErrorResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *customInterface) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _customInterface_interfaceTest_impl
		if err := irpcgen.DecInt(dec, &impl._IntFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_IntFunc_0_\" int: %w", err)
		}
		if err := irpcgen.DecString(dec, &impl._StringFunc_0_); err != nil {
			return fmt.Errorf("deserialize \"_StringFunc_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type customInterface: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_passAnonInterfaceReq struct {
	input interface {
		Age() int
		Name() string
	}
}

func (s _irpc_interfaceTest_passAnonInterfaceReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v interface {
		Age() int
		Name() string
	}) error { isNil := v == nil; if err := irpcgen.EncBool(enc, isNil); err != nil {
		return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
	}; if isNil {
		return nil
	}; _Age_0_ := v.Age(); if err := irpcgen.EncInt(enc, _Age_0_); err != nil {
		return fmt.Errorf("serialize \"v.Age()\" of type int: %w", err)
	}; _Name_0_ := v.Name(); if err := irpcgen.EncString(enc, _Name_0_); err != nil {
		return fmt.Errorf("serialize \"v.Name()\" of type string: %w", err)
	}; return nil }(e, s.input); err != nil {
		return fmt.Errorf("serialize \"input\" of type interface{Age() ( int);Name() ( string);}: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passAnonInterfaceReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *interface {
		Age() int
		Name() string
	}) error { var isNil bool; if err := irpcgen.DecBool(dec, &isNil); err != nil {
		return fmt.Errorf("deserialize isNil: %w:", err)
	}; if isNil {
		return nil
	}; var impl _iface_Age_Name_interfaceTest_impl; if err := irpcgen.DecInt(dec, &impl._Age_0_); err != nil {
		return fmt.Errorf("deserialize \"_Age_0_\" int: %w", err)
	}; if err := irpcgen.DecString(dec, &impl._Name_0_); err != nil {
		return fmt.Errorf("deserialize \"_Name_0_\" string: %w", err)
	}; *s = impl; return nil }(d, &s.input); err != nil {
		return fmt.Errorf("deserialize input of type interface{Age() ( int);Name() ( string);}: %w", err)
	}
	return nil
}

type _iface_Age_Name_interfaceTest_impl struct {
	_Age_0_  int
	_Name_0_ string
}

func (i _iface_Age_Name_interfaceTest_impl) Age() int {
	return i._Age_0_
}
func (i _iface_Age_Name_interfaceTest_impl) Name() string {
	return i._Name_0_
}

type _irpc_interfaceTest_passAnonInterfaceResp struct {
	p0 string
}

func (s _irpc_interfaceTest_passAnonInterfaceResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passAnonInterfaceResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	return nil
}

type _irpc_interfaceTest_passAnonInterfaceWithNamedParamsReq struct {
	input interface {
		a() (out.Uint8, int)
		b() out2.Uint8
		c() (out2.Uint8, error)
	}
}

func (s _irpc_interfaceTest_passAnonInterfaceWithNamedParamsReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v interface {
		a() (out.Uint8, int)
		b() out2.Uint8
		c() (out2.Uint8, error)
	}) error { isNil := v == nil; if err := irpcgen.EncBool(enc, isNil); err != nil {
		return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
	}; if isNil {
		return nil
	}; _a_0_, _a_1_ := v.a(); if err := irpcgen.EncUint8(enc, _a_0_); err != nil {
		return fmt.Errorf("serialize \"v.a()\" of type out.Uint8: %w", err)
	}; if err := irpcgen.EncInt(enc, _a_1_); err != nil {
		return fmt.Errorf("serialize \"v.a()\" of type int: %w", err)
	}; _b_0_ := v.b(); if err := irpcgen.EncUint8(enc, _b_0_); err != nil {
		return fmt.Errorf("serialize \"v.b()\" of type out2.Uint8: %w", err)
	}; _c_0_, _c_1_ := v.c(); if err := irpcgen.EncUint8(enc, _c_0_); err != nil {
		return fmt.Errorf("serialize \"v.c()\" of type out2.Uint8: %w", err)
	}; if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncBool(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(enc, _c_1_); err != nil {
		return fmt.Errorf("serialize \"v.c()\" of type error: %w", err)
	}; return nil }(e, s.input); err != nil {
		return fmt.Errorf("serialize \"input\" of type interface{a() ( out.Uint8, int);b() ( out2.Uint8);c() ( out2.Uint8, error);}: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passAnonInterfaceWithNamedParamsReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *interface {
		a() (out.Uint8, int)
		b() out2.Uint8
		c() (out2.Uint8, error)
	}) error { var isNil bool; if err := irpcgen.DecBool(dec, &isNil); err != nil {
		return fmt.Errorf("deserialize isNil: %w:", err)
	}; if isNil {
		return nil
	}; var impl _iface_a_b_c_interfaceTest_impl; if err := irpcgen.DecUint8(dec, &impl._a_0_); err != nil {
		return fmt.Errorf("deserialize \"_a_0_\" out.Uint8: %w", err)
	}; if err := irpcgen.DecInt(dec, &impl._a_1_); err != nil {
		return fmt.Errorf("deserialize \"_a_1_\" int: %w", err)
	}; if err := irpcgen.DecUint8(dec, &impl._b_0_); err != nil {
		return fmt.Errorf("deserialize \"_b_0_\" out2.Uint8: %w", err)
	}; if err := irpcgen.DecUint8(dec, &impl._c_0_); err != nil {
		return fmt.Errorf("deserialize \"_c_0_\" out2.Uint8: %w", err)
	}; if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecBool(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w:", err)
		}
		if isNil {
			return nil
		}
		var impl _error_interfaceTest_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(dec, &impl._c_1_); err != nil {
		return fmt.Errorf("deserialize \"_c_1_\" error: %w", err)
	}; *s = impl; return nil }(d, &s.input); err != nil {
		return fmt.Errorf("deserialize input of type interface{a() ( out.Uint8, int);b() ( out2.Uint8);c() ( out2.Uint8, error);}: %w", err)
	}
	return nil
}

type _iface_a_b_c_interfaceTest_impl struct {
	_a_0_ out.Uint8
	_a_1_ int
	_b_0_ out2.Uint8
	_c_0_ out2.Uint8
	_c_1_ error
}

func (i _iface_a_b_c_interfaceTest_impl) a() (out.Uint8, int) {
	return i._a_0_, i._a_1_
}
func (i _iface_a_b_c_interfaceTest_impl) b() out2.Uint8 {
	return i._b_0_
}
func (i _iface_a_b_c_interfaceTest_impl) c() (out2.Uint8, error) {
	return i._c_0_, i._c_1_
}

type _irpc_interfaceTest_passAnonInterfaceWithNamedParamsResp struct {
	p0 string
}

func (s _irpc_interfaceTest_passAnonInterfaceWithNamedParamsResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	return nil
}
func (s *_irpc_interfaceTest_passAnonInterfaceWithNamedParamsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	return nil
}

var _customInterfaceIrpcId = []byte{
	0xe6, 0x69, 0x8c, 0xb1, 0xca, 0xc2, 0xb8, 0x7f,
	0x60, 0xf9, 0xa4, 0xf3, 0x5a, 0x2c, 0xe9, 0x8d,
	0xa2, 0x33, 0xbd, 0x91, 0x5a, 0xf1, 0x25, 0x4b,
	0x48, 0xee, 0x2d, 0xfd, 0xeb, 0xe2, 0xa3, 0x57,
}

type customInterfaceIrpcService struct {
	impl customInterface
}

func newCustomInterfaceIrpcService(impl customInterface) *customInterfaceIrpcService {
	return &customInterfaceIrpcService{
		impl: impl,
	}
}
func (s *customInterfaceIrpcService) Id() []byte {
	return _customInterfaceIrpcId
}
func (s *customInterfaceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // IntFunc
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_customInterface_IntFuncResp
				resp.p0 = s.impl.IntFunc()
				return resp
			}, nil
		}, nil
	case 1: // StringFunc
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_customInterface_StringFuncResp
				resp.p0 = s.impl.StringFunc()
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// customInterfaceIrpcClient implements customInterface
//
// todo: currently we are also generating service and client for this interface. perhaps we don't want that?
type customInterfaceIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newCustomInterfaceIrpcClient(endpoint irpcgen.Endpoint) (*customInterfaceIrpcClient, error) {
	if err := endpoint.RegisterClient(_customInterfaceIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &customInterfaceIrpcClient{endpoint: endpoint}, nil
}
func (_c *customInterfaceIrpcClient) IntFunc() int {
	var resp _irpc_customInterface_IntFuncResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _customInterfaceIrpcId, 0, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *customInterfaceIrpcClient) StringFunc() string {
	var resp _irpc_customInterface_StringFuncResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _customInterfaceIrpcId, 1, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_customInterface_IntFuncResp struct {
	p0 int
}

func (s _irpc_customInterface_IntFuncResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_customInterface_IntFuncResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}

type _irpc_customInterface_StringFuncResp struct {
	p0 string
}

func (s _irpc_customInterface_StringFuncResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	return nil
}
func (s *_irpc_customInterface_StringFuncResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	return nil
}
