// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type mapTestIrpcService struct {
	impl mapTest
	id   []byte
}

func newMapTestIrpcService(impl mapTest) *mapTestIrpcService {
	return &mapTestIrpcService{
		impl: impl,
		id: []byte{
			0xc2, 0x34, 0x85, 0xc2, 0xbf, 0xe4, 0xc5, 0x2e,
			0xbd, 0x25, 0x41, 0xa9, 0x4a, 0xbe, 0x43, 0x46,
			0x75, 0xb3, 0x20, 0xc2, 0x21, 0x4d, 0x60, 0x09,
			0x6d, 0x74, 0xbf, 0x3e, 0x26, 0xec, 0x5b, 0x48,
		},
	}
}
func (s *mapTestIrpcService) Id() []byte {
	return s.id
}
func (s *mapTestIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // mapSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_mapTest_mapSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_mapTest_mapSumResp
				resp.keysSum, resp.valsSum = s.impl.mapSum(args.in)
				return resp
			}, nil
		}, nil
	case 1: // sumStructs
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_mapTest_sumStructsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_mapTest_sumStructsResp
				resp.keysSum, resp.valsSum = s.impl.sumStructs(args.in)
				return resp
			}, nil
		}, nil
	case 2: // sumSlices
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_mapTest_sumSlicesReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_mapTest_sumSlicesResp
				resp.keysSum, resp.valsSum = s.impl.sumSlices(args.in)
				return resp
			}, nil
		}, nil
	case 3: // namedMapInc
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_mapTest_namedMapIncReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_mapTest_namedMapIncResp
				resp.p0 = s.impl.namedMapInc(args.in)
				return resp
			}, nil
		}, nil
	case 4: // namedKeySum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_mapTest_namedKeySumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_mapTest_namedKeySumResp
				resp.p0 = s.impl.namedKeySum(args.in)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// mapTestIrpcClient implements mapTest
type mapTestIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newMapTestIrpcClient(endpoint irpcgen.Endpoint) (*mapTestIrpcClient, error) {
	id := []byte{
		0xc2, 0x34, 0x85, 0xc2, 0xbf, 0xe4, 0xc5, 0x2e,
		0xbd, 0x25, 0x41, 0xa9, 0x4a, 0xbe, 0x43, 0x46,
		0x75, 0xb3, 0x20, 0xc2, 0x21, 0x4d, 0x60, 0x09,
		0x6d, 0x74, 0xbf, 0x3e, 0x26, 0xec, 0x5b, 0x48,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &mapTestIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *mapTestIrpcClient) mapSum(in map[int]float64) (keysSum int, valsSum float64) {
	var req = _irpc_mapTest_mapSumReq{
		in: in,
	}
	var resp _irpc_mapTest_mapSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.keysSum, resp.valsSum
}
func (_c *mapTestIrpcClient) sumStructs(in map[intStruct]intStruct) (keysSum int, valsSum int) {
	var req = _irpc_mapTest_sumStructsReq{
		in: in,
	}
	var resp _irpc_mapTest_sumStructsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.keysSum, resp.valsSum
}
func (_c *mapTestIrpcClient) sumSlices(in map[intStruct][]intStruct) (keysSum int, valsSum int) {
	var req = _irpc_mapTest_sumSlicesReq{
		in: in,
	}
	var resp _irpc_mapTest_sumSlicesResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.keysSum, resp.valsSum
}
func (_c *mapTestIrpcClient) namedMapInc(in namedIntFloatMap) namedIntFloatMap {
	var req = _irpc_mapTest_namedMapIncReq{
		in: in,
	}
	var resp _irpc_mapTest_namedMapIncResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *mapTestIrpcClient) namedKeySum(in map[mapNamedInt]mapNamedFloat64) mapNamedFloat64 {
	var req = _irpc_mapTest_namedKeySumReq{
		in: in,
	}
	var resp _irpc_mapTest_namedKeySumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 4, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_mapTest_mapSumReq struct {
	in map[int]float64
}

func (s _irpc_mapTest_mapSumReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.in map[int]float64
		if err := e.Len(len(s.in)); err != nil {
			return fmt.Errorf("serialize len(s.in) of type \"int\": %w", err)
		}
		for k, v := range s.in {
			if err := e.VarInt(k); err != nil {
				return fmt.Errorf("serialize k of type \"int\": %w", err)
			}
			if err := e.Float64le(v); err != nil {
				return fmt.Errorf("serialize v of type \"float64\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_mapTest_mapSumReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.in map[int]float64
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.in = make(map[int]float64, l)
		for range l {
			var k int
			if err := d.VarInt(&k); err != nil {
				return fmt.Errorf("deserialize k of type \"int\": %w", err)
			}

			var v float64
			if err := d.Float64le(&v); err != nil {
				return fmt.Errorf("deserialize v of type \"float64\": %w", err)
			}

			s.in[k] = v
		}
	}
	return nil
}

type _irpc_mapTest_mapSumResp struct {
	keysSum int
	valsSum float64
}

func (s _irpc_mapTest_mapSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.keysSum); err != nil {
		return fmt.Errorf("serialize s.keysSum of type \"int\": %w", err)
	}
	if err := e.Float64le(s.valsSum); err != nil {
		return fmt.Errorf("serialize s.valsSum of type \"float64\": %w", err)
	}
	return nil
}
func (s *_irpc_mapTest_mapSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.keysSum); err != nil {
		return fmt.Errorf("deserialize s.keysSum of type \"int\": %w", err)
	}
	if err := d.Float64le(&s.valsSum); err != nil {
		return fmt.Errorf("deserialize s.valsSum of type \"float64\": %w", err)
	}
	return nil
}

type _irpc_mapTest_sumStructsReq struct {
	in map[intStruct]intStruct
}

func (s _irpc_mapTest_sumStructsReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.in map[intStruct]intStruct
		if err := e.Len(len(s.in)); err != nil {
			return fmt.Errorf("serialize len(s.in) of type \"int\": %w", err)
		}
		for k, v := range s.in {
			if err := e.VarInt(k.i); err != nil {
				return fmt.Errorf("serialize k.i of type \"int\": %w", err)
			}
			if err := e.VarInt(k.j); err != nil {
				return fmt.Errorf("serialize k.j of type \"int\": %w", err)
			}
			if err := e.VarInt(k.k); err != nil {
				return fmt.Errorf("serialize k.k of type \"int\": %w", err)
			}
			if err := e.VarInt(k.l); err != nil {
				return fmt.Errorf("serialize k.l of type \"int\": %w", err)
			}
			if err := e.VarInt(v.i); err != nil {
				return fmt.Errorf("serialize v.i of type \"int\": %w", err)
			}
			if err := e.VarInt(v.j); err != nil {
				return fmt.Errorf("serialize v.j of type \"int\": %w", err)
			}
			if err := e.VarInt(v.k); err != nil {
				return fmt.Errorf("serialize v.k of type \"int\": %w", err)
			}
			if err := e.VarInt(v.l); err != nil {
				return fmt.Errorf("serialize v.l of type \"int\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_mapTest_sumStructsReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.in map[intStruct]intStruct
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.in = make(map[intStruct]intStruct, l)
		for range l {
			var k intStruct
			if err := d.VarInt(&k.i); err != nil {
				return fmt.Errorf("deserialize k.i of type \"int\": %w", err)
			}
			if err := d.VarInt(&k.j); err != nil {
				return fmt.Errorf("deserialize k.j of type \"int\": %w", err)
			}
			if err := d.VarInt(&k.k); err != nil {
				return fmt.Errorf("deserialize k.k of type \"int\": %w", err)
			}
			if err := d.VarInt(&k.l); err != nil {
				return fmt.Errorf("deserialize k.l of type \"int\": %w", err)
			}

			var v intStruct
			if err := d.VarInt(&v.i); err != nil {
				return fmt.Errorf("deserialize v.i of type \"int\": %w", err)
			}
			if err := d.VarInt(&v.j); err != nil {
				return fmt.Errorf("deserialize v.j of type \"int\": %w", err)
			}
			if err := d.VarInt(&v.k); err != nil {
				return fmt.Errorf("deserialize v.k of type \"int\": %w", err)
			}
			if err := d.VarInt(&v.l); err != nil {
				return fmt.Errorf("deserialize v.l of type \"int\": %w", err)
			}

			s.in[k] = v
		}
	}
	return nil
}

type _irpc_mapTest_sumStructsResp struct {
	keysSum int
	valsSum int
}

func (s _irpc_mapTest_sumStructsResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.keysSum); err != nil {
		return fmt.Errorf("serialize s.keysSum of type \"int\": %w", err)
	}
	if err := e.VarInt(s.valsSum); err != nil {
		return fmt.Errorf("serialize s.valsSum of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_mapTest_sumStructsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.keysSum); err != nil {
		return fmt.Errorf("deserialize s.keysSum of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.valsSum); err != nil {
		return fmt.Errorf("deserialize s.valsSum of type \"int\": %w", err)
	}
	return nil
}

type _irpc_mapTest_sumSlicesReq struct {
	in map[intStruct][]intStruct
}

func (s _irpc_mapTest_sumSlicesReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.in map[intStruct][]intStruct
		if err := e.Len(len(s.in)); err != nil {
			return fmt.Errorf("serialize len(s.in) of type \"int\": %w", err)
		}
		for k, v := range s.in {
			if err := e.VarInt(k.i); err != nil {
				return fmt.Errorf("serialize k.i of type \"int\": %w", err)
			}
			if err := e.VarInt(k.j); err != nil {
				return fmt.Errorf("serialize k.j of type \"int\": %w", err)
			}
			if err := e.VarInt(k.k); err != nil {
				return fmt.Errorf("serialize k.k of type \"int\": %w", err)
			}
			if err := e.VarInt(k.l); err != nil {
				return fmt.Errorf("serialize k.l of type \"int\": %w", err)
			}
			{ // v []intStruct
				if err := e.Len(len(v)); err != nil {
					return fmt.Errorf("serialize len(v) of type \"int\": %w", err)
				}
				for _, v := range v {
					if err := e.VarInt(v.i); err != nil {
						return fmt.Errorf("serialize v.i of type \"int\": %w", err)
					}
					if err := e.VarInt(v.j); err != nil {
						return fmt.Errorf("serialize v.j of type \"int\": %w", err)
					}
					if err := e.VarInt(v.k); err != nil {
						return fmt.Errorf("serialize v.k of type \"int\": %w", err)
					}
					if err := e.VarInt(v.l); err != nil {
						return fmt.Errorf("serialize v.l of type \"int\": %w", err)
					}
				}
			}
		}
	}
	return nil
}
func (s *_irpc_mapTest_sumSlicesReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.in map[intStruct][]intStruct
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.in = make(map[intStruct][]intStruct, l)
		for range l {
			var k intStruct
			if err := d.VarInt(&k.i); err != nil {
				return fmt.Errorf("deserialize k.i of type \"int\": %w", err)
			}
			if err := d.VarInt(&k.j); err != nil {
				return fmt.Errorf("deserialize k.j of type \"int\": %w", err)
			}
			if err := d.VarInt(&k.k); err != nil {
				return fmt.Errorf("deserialize k.k of type \"int\": %w", err)
			}
			if err := d.VarInt(&k.l); err != nil {
				return fmt.Errorf("deserialize k.l of type \"int\": %w", err)
			}

			var v []intStruct
			{ // v []intStruct
				var l int
				if err := d.Len(&l); err != nil {
					return fmt.Errorf("deserialize l of type \"int\": %w", err)
				}
				v = make([]intStruct, l)
				for i := range l {
					if err := d.VarInt(&v[i].i); err != nil {
						return fmt.Errorf("deserialize v[i].i of type \"int\": %w", err)
					}
					if err := d.VarInt(&v[i].j); err != nil {
						return fmt.Errorf("deserialize v[i].j of type \"int\": %w", err)
					}
					if err := d.VarInt(&v[i].k); err != nil {
						return fmt.Errorf("deserialize v[i].k of type \"int\": %w", err)
					}
					if err := d.VarInt(&v[i].l); err != nil {
						return fmt.Errorf("deserialize v[i].l of type \"int\": %w", err)
					}
				}
			}

			s.in[k] = v
		}
	}
	return nil
}

type _irpc_mapTest_sumSlicesResp struct {
	keysSum int
	valsSum int
}

func (s _irpc_mapTest_sumSlicesResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.keysSum); err != nil {
		return fmt.Errorf("serialize s.keysSum of type \"int\": %w", err)
	}
	if err := e.VarInt(s.valsSum); err != nil {
		return fmt.Errorf("serialize s.valsSum of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_mapTest_sumSlicesResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.keysSum); err != nil {
		return fmt.Errorf("deserialize s.keysSum of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.valsSum); err != nil {
		return fmt.Errorf("deserialize s.valsSum of type \"int\": %w", err)
	}
	return nil
}

type _irpc_mapTest_namedMapIncReq struct {
	in namedIntFloatMap
}

func (s _irpc_mapTest_namedMapIncReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.in namedIntFloatMap
		if err := e.Len(len(s.in)); err != nil {
			return fmt.Errorf("serialize len(s.in) of type \"int\": %w", err)
		}
		for k, v := range s.in {
			if err := e.VarInt(k); err != nil {
				return fmt.Errorf("serialize k of type \"int\": %w", err)
			}
			if err := e.Float64le(v); err != nil {
				return fmt.Errorf("serialize v of type \"float64\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_mapTest_namedMapIncReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.in namedIntFloatMap
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.in = make(namedIntFloatMap, l)
		for range l {
			var k int
			if err := d.VarInt(&k); err != nil {
				return fmt.Errorf("deserialize k of type \"int\": %w", err)
			}

			var v float64
			if err := d.Float64le(&v); err != nil {
				return fmt.Errorf("deserialize v of type \"float64\": %w", err)
			}

			s.in[k] = v
		}
	}
	return nil
}

type _irpc_mapTest_namedMapIncResp struct {
	p0 namedIntFloatMap
}

func (s _irpc_mapTest_namedMapIncResp) Serialize(e *irpcgen.Encoder) error {
	{ // s.p0 namedIntFloatMap
		if err := e.Len(len(s.p0)); err != nil {
			return fmt.Errorf("serialize len(s.p0) of type \"int\": %w", err)
		}
		for k, v := range s.p0 {
			if err := e.VarInt(k); err != nil {
				return fmt.Errorf("serialize k of type \"int\": %w", err)
			}
			if err := e.Float64le(v); err != nil {
				return fmt.Errorf("serialize v of type \"float64\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_mapTest_namedMapIncResp) Deserialize(d *irpcgen.Decoder) error {
	{ // s.p0 namedIntFloatMap
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.p0 = make(namedIntFloatMap, l)
		for range l {
			var k int
			if err := d.VarInt(&k); err != nil {
				return fmt.Errorf("deserialize k of type \"int\": %w", err)
			}

			var v float64
			if err := d.Float64le(&v); err != nil {
				return fmt.Errorf("deserialize v of type \"float64\": %w", err)
			}

			s.p0[k] = v
		}
	}
	return nil
}

type _irpc_mapTest_namedKeySumReq struct {
	in map[mapNamedInt]mapNamedFloat64
}

func (s _irpc_mapTest_namedKeySumReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.in map[mapNamedInt]mapNamedFloat64
		if err := e.Len(len(s.in)); err != nil {
			return fmt.Errorf("serialize len(s.in) of type \"int\": %w", err)
		}
		for k, v := range s.in {
			if err := e.VarInt(int(k)); err != nil {
				return fmt.Errorf("serialize k of type \"mapNamedInt\": %w", err)
			}
			if err := e.Float64le(float64(v)); err != nil {
				return fmt.Errorf("serialize v of type \"mapNamedFloat64\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_mapTest_namedKeySumReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.in map[mapNamedInt]mapNamedFloat64
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.in = make(map[mapNamedInt]mapNamedFloat64, l)
		for range l {
			var k mapNamedInt
			if err := d.VarInt((*int)(&k)); err != nil {
				return fmt.Errorf("deserialize k of type \"mapNamedInt\": %w", err)
			}

			var v mapNamedFloat64
			if err := d.Float64le((*float64)(&v)); err != nil {
				return fmt.Errorf("deserialize v of type \"mapNamedFloat64\": %w", err)
			}

			s.in[k] = v
		}
	}
	return nil
}

type _irpc_mapTest_namedKeySumResp struct {
	p0 mapNamedFloat64
}

func (s _irpc_mapTest_namedKeySumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(float64(s.p0)); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"mapNamedFloat64\": %w", err)
	}
	return nil
}
func (s *_irpc_mapTest_namedKeySumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le((*float64)(&s.p0)); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"mapNamedFloat64\": %w", err)
	}
	return nil
}
