// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/named.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _namedTestIrpcId = []byte{
	0xbd, 0xab, 0xfc, 0xad, 0x05, 0xfe, 0x7e, 0x8d,
	0xd8, 0x7f, 0x2e, 0x5b, 0xb0, 0xfd, 0x4a, 0x45,
	0x1e, 0xcc, 0x06, 0x79, 0x97, 0x5c, 0x82, 0xcd,
	0x05, 0xfb, 0x54, 0xc1, 0xf2, 0xc3, 0x3f, 0x0a,
}

type namedTestIrpcService struct {
	impl namedTest
}

func newNamedTestIrpcService(impl namedTest) *namedTestIrpcService {
	return &namedTestIrpcService{
		impl: impl,
	}
}
func (s *namedTestIrpcService) Id() []byte {
	return _namedTestIrpcId
}
func (s *namedTestIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // isWeekend
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_isWeekendReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_isWeekendResp
				resp.p0 = s.impl.isWeekend(args.wd)
				return resp
			}, nil
		}, nil
	case 1: // isWeekend2
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_isWeekend2Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_isWeekend2Resp
				resp.p0 = s.impl.isWeekend2(args.wd)
				return resp
			}, nil
		}, nil
	case 2: // containsSaturday
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_containsSaturdayReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_containsSaturdayResp
				resp.p0 = s.impl.containsSaturday(args.wds)
				return resp
			}, nil
		}, nil
	case 3: // containsSaturday2
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_containsSaturday2Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_containsSaturday2Resp
				resp.p0 = s.impl.containsSaturday2(args.wds)
				return resp
			}, nil
		}, nil
	case 4: // namedBytesSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_namedBytesSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_namedBytesSumResp
				resp.p0 = s.impl.namedBytesSum(args.nb)
				return resp
			}, nil
		}, nil
	case 5: // namedMapSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_namedMapSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_namedMapSumResp
				resp.p02 = s.impl.namedMapSum(args.p0)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// namedTestIrpcClient implements namedTest
type namedTestIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newNamedTestIrpcClient(endpoint irpcgen.Endpoint) (*namedTestIrpcClient, error) {
	if err := endpoint.RegisterClient(_namedTestIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &namedTestIrpcClient{endpoint: endpoint}, nil
}
func (_c *namedTestIrpcClient) isWeekend(wd weekDay) bool {
	var req = _irpc_namedTest_isWeekendReq{
		wd: wd,
	}
	var resp _irpc_namedTest_isWeekendResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) isWeekend2(wd weekDay2) bool {
	var req = _irpc_namedTest_isWeekend2Req{
		wd: wd,
	}
	var resp _irpc_namedTest_isWeekend2Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) containsSaturday(wds []weekDay) bool {
	var req = _irpc_namedTest_containsSaturdayReq{
		wds: wds,
	}
	var resp _irpc_namedTest_containsSaturdayResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) containsSaturday2(wds namedWeekDaysSliceType) bool {
	var req = _irpc_namedTest_containsSaturday2Req{
		wds: wds,
	}
	var resp _irpc_namedTest_containsSaturday2Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) namedBytesSum(nb namedByteSliceType) int {
	var req = _irpc_namedTest_namedBytesSumReq{
		nb: nb,
	}
	var resp _irpc_namedTest_namedBytesSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 4, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) namedMapSum(p0 namedMap) float64 {
	var req = _irpc_namedTest_namedMapSumReq{
		p0: p0,
	}
	var resp _irpc_namedTest_namedMapSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p02
}

type _irpc_namedTest_isWeekendReq struct {
	wd weekDay
}

func (s _irpc_namedTest_isWeekendReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncUint8(e, s.wd); err != nil {
		return fmt.Errorf("serialize \"wd\" of type weekDay: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekendReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecUint8(d, &s.wd); err != nil {
		return fmt.Errorf("deserialize wd of type weekDay: %w", err)
	}
	return nil
}

type _irpc_namedTest_isWeekendResp struct {
	p0 bool
}

func (s _irpc_namedTest_isWeekendResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBool(e, s.p0); err != nil {
		return fmt.Errorf("serialize type bool: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekendResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBool(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type bool: %w", err)
	}
	return nil
}

type _irpc_namedTest_isWeekend2Req struct {
	wd weekDay2
}

func (s _irpc_namedTest_isWeekend2Req) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncUint8(e, s.wd); err != nil {
		return fmt.Errorf("serialize \"wd\" of type weekDay2: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekend2Req) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecUint8(d, &s.wd); err != nil {
		return fmt.Errorf("deserialize wd of type weekDay2: %w", err)
	}
	return nil
}

type _irpc_namedTest_isWeekend2Resp struct {
	p0 bool
}

func (s _irpc_namedTest_isWeekend2Resp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBool(e, s.p0); err != nil {
		return fmt.Errorf("serialize type bool: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekend2Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBool(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type bool: %w", err)
	}
	return nil
}

type _irpc_namedTest_containsSaturdayReq struct {
	wds []weekDay
}

func (s _irpc_namedTest_containsSaturdayReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, sl []weekDay) error {
		return irpcgen.EncSlice(enc, "weekDay", irpcgen.EncUint8, sl)
	}(e, s.wds); err != nil {
		return fmt.Errorf("serialize \"wds\" of type []weekDay: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturdayReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, sl *[]weekDay) error {
		return irpcgen.DecSlice(dec, "weekDay", irpcgen.DecUint8, sl)
	}(d, &s.wds); err != nil {
		return fmt.Errorf("deserialize wds of type []weekDay: %w", err)
	}
	return nil
}

type _irpc_namedTest_containsSaturdayResp struct {
	p0 bool
}

func (s _irpc_namedTest_containsSaturdayResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBool(e, s.p0); err != nil {
		return fmt.Errorf("serialize type bool: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturdayResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBool(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type bool: %w", err)
	}
	return nil
}

type _irpc_namedTest_containsSaturday2Req struct {
	wds namedWeekDaysSliceType
}

func (s _irpc_namedTest_containsSaturday2Req) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, sl namedWeekDaysSliceType) error {
		return irpcgen.EncSlice(enc, "weekDay2", irpcgen.EncUint8, sl)
	}(e, s.wds); err != nil {
		return fmt.Errorf("serialize \"wds\" of type namedWeekDaysSliceType: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturday2Req) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, sl *namedWeekDaysSliceType) error {
		return irpcgen.DecSlice(dec, "weekDay2", irpcgen.DecUint8, sl)
	}(d, &s.wds); err != nil {
		return fmt.Errorf("deserialize wds of type namedWeekDaysSliceType: %w", err)
	}
	return nil
}

type _irpc_namedTest_containsSaturday2Resp struct {
	p0 bool
}

func (s _irpc_namedTest_containsSaturday2Resp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBool(e, s.p0); err != nil {
		return fmt.Errorf("serialize type bool: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturday2Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBool(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type bool: %w", err)
	}
	return nil
}

type _irpc_namedTest_namedBytesSumReq struct {
	nb namedByteSliceType
}

func (s _irpc_namedTest_namedBytesSumReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncByteSlice(e, s.nb); err != nil {
		return fmt.Errorf("serialize \"nb\" of type namedByteSliceType: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_namedBytesSumReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecByteSlice(d, &s.nb); err != nil {
		return fmt.Errorf("deserialize nb of type namedByteSliceType: %w", err)
	}
	return nil
}

type _irpc_namedTest_namedBytesSumResp struct {
	p0 int
}

func (s _irpc_namedTest_namedBytesSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_namedBytesSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}

type _irpc_namedTest_namedMapSumReq struct {
	p0 namedMap
}

func (s _irpc_namedTest_namedMapSumReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, m namedMap) error {
		return irpcgen.EncMap(enc, m, "int", irpcgen.EncInt, "float64", irpcgen.EncFloat64)
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize \"p0\" of type namedMap: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_namedMapSumReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, m *namedMap) error {
		return irpcgen.DecMap(dec, m, "int", irpcgen.DecInt, "float64", irpcgen.DecFloat64)
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize p0 of type namedMap: %w", err)
	}
	return nil
}

type _irpc_namedTest_namedMapSumResp struct {
	p02 float64
}

func (s _irpc_namedTest_namedMapSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncFloat64(e, s.p02); err != nil {
		return fmt.Errorf("serialize type float64: %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_namedMapSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecFloat64(d, &s.p02); err != nil {
		return fmt.Errorf("deserialize type float64: %w", err)
	}
	return nil
}
