// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/named.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _namedTestIrpcId = []byte{
	0xec, 0x88, 0x05, 0xa2, 0xec, 0x9e, 0xa6, 0x05,
	0x1c, 0x7d, 0x72, 0x23, 0x6a, 0x5b, 0x87, 0xe4,
	0x57, 0x85, 0xe8, 0x82, 0xb0, 0xd6, 0xd5, 0x14,
	0x9a, 0x0c, 0xdb, 0xdf, 0xd4, 0x8e, 0x06, 0x3f,
}

type namedTestIrpcService struct {
	impl namedTest
}

func newNamedTestIrpcService(impl namedTest) *namedTestIrpcService {
	return &namedTestIrpcService{
		impl: impl,
	}
}
func (s *namedTestIrpcService) Id() []byte {
	return _namedTestIrpcId
}
func (s *namedTestIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // isWeekend
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_isWeekendReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_isWeekendResp
				resp.p0 = s.impl.isWeekend(args.wd)
				return resp
			}, nil
		}, nil
	case 1: // isWeekend2
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_isWeekend2Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_isWeekend2Resp
				resp.p0 = s.impl.isWeekend2(args.wd)
				return resp
			}, nil
		}, nil
	case 2: // containsSaturday
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_containsSaturdayReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_containsSaturdayResp
				resp.p0 = s.impl.containsSaturday(args.wds)
				return resp
			}, nil
		}, nil
	case 3: // containsSaturday2
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_containsSaturday2Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_containsSaturday2Resp
				resp.p0 = s.impl.containsSaturday2(args.wds)
				return resp
			}, nil
		}, nil
	case 4: // namedBytesSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_namedBytesSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_namedBytesSumResp
				resp.p0 = s.impl.namedBytesSum(args.nb)
				return resp
			}, nil
		}, nil
	case 5: // namedMapSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_namedTest_namedMapSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_namedTest_namedMapSumResp
				resp.p02 = s.impl.namedMapSum(args.p0)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// namedTestIrpcClient implements namedTest
type namedTestIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newNamedTestIrpcClient(endpoint irpcgen.Endpoint) (*namedTestIrpcClient, error) {
	if err := endpoint.RegisterClient(_namedTestIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &namedTestIrpcClient{endpoint: endpoint}, nil
}
func (_c *namedTestIrpcClient) isWeekend(wd weekDay) bool {
	var req = _irpc_namedTest_isWeekendReq{
		wd: wd,
	}
	var resp _irpc_namedTest_isWeekendResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) isWeekend2(wd weekDay2) bool {
	var req = _irpc_namedTest_isWeekend2Req{
		wd: wd,
	}
	var resp _irpc_namedTest_isWeekend2Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) containsSaturday(wds []weekDay) bool {
	var req = _irpc_namedTest_containsSaturdayReq{
		wds: wds,
	}
	var resp _irpc_namedTest_containsSaturdayResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) containsSaturday2(wds namedWeekDaysSliceType) bool {
	var req = _irpc_namedTest_containsSaturday2Req{
		wds: wds,
	}
	var resp _irpc_namedTest_containsSaturday2Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) namedBytesSum(nb namedByteSliceType) int {
	var req = _irpc_namedTest_namedBytesSumReq{
		nb: nb,
	}
	var resp _irpc_namedTest_namedBytesSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 4, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *namedTestIrpcClient) namedMapSum(p0 namedMap) float64 {
	var req = _irpc_namedTest_namedMapSumReq{
		p0: p0,
	}
	var resp _irpc_namedTest_namedMapSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _namedTestIrpcId, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p02
}

type _irpc_namedTest_isWeekendReq struct {
	wd weekDay
}

func (s _irpc_namedTest_isWeekendReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.wd)); err != nil {
		return fmt.Errorf("serialize s.wd of type \"weekDay\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekendReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.wd)); err != nil {
		return fmt.Errorf("deserialize s.wd of type \"weekDay\": %w", err)
	}
	return nil
}

type _irpc_namedTest_isWeekendResp struct {
	p0 bool
}

func (s _irpc_namedTest_isWeekendResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Bool(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekendResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Bool(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}

type _irpc_namedTest_isWeekend2Req struct {
	wd weekDay2
}

func (s _irpc_namedTest_isWeekend2Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.wd)); err != nil {
		return fmt.Errorf("serialize s.wd of type \"weekDay2\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekend2Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.wd)); err != nil {
		return fmt.Errorf("deserialize s.wd of type \"weekDay2\": %w", err)
	}
	return nil
}

type _irpc_namedTest_isWeekend2Resp struct {
	p0 bool
}

func (s _irpc_namedTest_isWeekend2Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Bool(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_isWeekend2Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Bool(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}

type _irpc_namedTest_containsSaturdayReq struct {
	wds []weekDay
}

func (s _irpc_namedTest_containsSaturdayReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.wds []weekDay
		if err := e.Len(len(s.wds)); err != nil {
			return fmt.Errorf("serialize len(s.wds) of type \"int\": %w", err)
		}
		for _, v := range s.wds {
			if err := e.Uint8(uint8(v)); err != nil {
				return fmt.Errorf("serialize v of type \"weekDay\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturdayReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.wds []weekDay
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.wds = make([]weekDay, l)
		for i := range l {
			if err := d.Uint8((*uint8)(&s.wds[i])); err != nil {
				return fmt.Errorf("deserialize s.wds[i] of type \"weekDay\": %w", err)
			}
		}
	}
	return nil
}

type _irpc_namedTest_containsSaturdayResp struct {
	p0 bool
}

func (s _irpc_namedTest_containsSaturdayResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Bool(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturdayResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Bool(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}

type _irpc_namedTest_containsSaturday2Req struct {
	wds namedWeekDaysSliceType
}

func (s _irpc_namedTest_containsSaturday2Req) Serialize(e *irpcgen.Encoder) error {
	{ // s.wds namedWeekDaysSliceType
		if err := e.Len(len(s.wds)); err != nil {
			return fmt.Errorf("serialize len(s.wds) of type \"int\": %w", err)
		}
		for _, v := range s.wds {
			if err := e.Uint8(uint8(v)); err != nil {
				return fmt.Errorf("serialize v of type \"weekDay2\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturday2Req) Deserialize(d *irpcgen.Decoder) error {
	{ // s.wds namedWeekDaysSliceType
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.wds = make(namedWeekDaysSliceType, l)
		for i := range l {
			if err := d.Uint8((*uint8)(&s.wds[i])); err != nil {
				return fmt.Errorf("deserialize s.wds[i] of type \"weekDay2\": %w", err)
			}
		}
	}
	return nil
}

type _irpc_namedTest_containsSaturday2Resp struct {
	p0 bool
}

func (s _irpc_namedTest_containsSaturday2Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Bool(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_containsSaturday2Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Bool(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"bool\": %w", err)
	}
	return nil
}

type _irpc_namedTest_namedBytesSumReq struct {
	nb namedByteSliceType
}

func (s _irpc_namedTest_namedBytesSumReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.ByteSlice([]byte(s.nb)); err != nil {
		return fmt.Errorf("serialize s.nb of type \"namedByteSliceType\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_namedBytesSumReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.ByteSlice((*[]byte)(&s.nb)); err != nil {
		return fmt.Errorf("deserialize s.nb of type \"namedByteSliceType\": %w", err)
	}
	return nil
}

type _irpc_namedTest_namedBytesSumResp struct {
	p0 int
}

func (s _irpc_namedTest_namedBytesSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_namedBytesSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_namedTest_namedMapSumReq struct {
	p0 namedMap
}

func (s _irpc_namedTest_namedMapSumReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.p0 namedMap
		if err := e.Len(len(s.p0)); err != nil {
			return fmt.Errorf("serialize len(s.p0) of type \"int\": %w", err)
		}
		for k, v := range s.p0 {
			if err := e.VarInt(k); err != nil {
				return fmt.Errorf("serialize k of type \"int\": %w", err)
			}
			if err := e.Float64le(v); err != nil {
				return fmt.Errorf("serialize v of type \"float64\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_namedTest_namedMapSumReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.p0 namedMap
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.p0 = make(namedMap, l)
		for range l {
			var k int
			if err := d.VarInt(&k); err != nil {
				return fmt.Errorf("deserialize k of type \"int\": %w", err)
			}

			var v float64
			if err := d.Float64le(&v); err != nil {
				return fmt.Errorf("deserialize v of type \"float64\": %w", err)
			}

			s.p0[k] = v
		}
	}
	return nil
}

type _irpc_namedTest_namedMapSumResp struct {
	p02 float64
}

func (s _irpc_namedTest_namedMapSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(s.p02); err != nil {
		return fmt.Errorf("serialize s.p02 of type \"float64\": %w", err)
	}
	return nil
}
func (s *_irpc_namedTest_namedMapSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le(&s.p02); err != nil {
		return fmt.Errorf("deserialize s.p02 of type \"float64\": %w", err)
	}
	return nil
}
