// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/cmd/irpc/test/out"
	"github.com/marben/irpc/irpcgen"
)

type outsideTestIRpcService struct {
	impl outsideTest
	id   []byte
}

func newOutsideTestIRpcService(impl outsideTest) *outsideTestIRpcService {
	return &outsideTestIRpcService{
		impl: impl,
		id: []byte{
			0xe2, 0x91, 0xb8, 0xe9, 0x5e, 0xa8, 0x6e, 0x88,
			0xea, 0x86, 0x48, 0xe1, 0x8e, 0x09, 0x6e, 0xbf,
			0xa1, 0xe5, 0xce, 0xe7, 0xb4, 0xfd, 0x1e, 0x30,
			0x1c, 0x4e, 0x0e, 0x51, 0x4c, 0xa3, 0x05, 0x59,
		},
	}
}
func (s *outsideTestIRpcService) Id() []byte {
	return s.id
}
func (s *outsideTestIRpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // addUint8
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_outsideTestaddUint8Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _Irpc_outsideTestaddUint8Resp
				resp.Param0 = s.impl.addUint8(args.Param0_a, args.Param0_b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

type outsideTestIRpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newOutsideTestIRpcClient(endpoint irpcgen.Endpoint) (*outsideTestIRpcClient, error) {
	id := []byte{
		0xe2, 0x91, 0xb8, 0xe9, 0x5e, 0xa8, 0x6e, 0x88,
		0xea, 0x86, 0x48, 0xe1, 0x8e, 0x09, 0x6e, 0xbf,
		0xa1, 0xe5, 0xce, 0xe7, 0xb4, 0xfd, 0x1e, 0x30,
		0x1c, 0x4e, 0x0e, 0x51, 0x4c, 0xa3, 0x05, 0x59,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &outsideTestIRpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *outsideTestIRpcClient) addUint8(a out.Uint8, b out.Uint8) out.Uint8 {
	var req = _Irpc_outsideTestaddUint8Req{
		Param0_a: a,
		Param0_b: b,
	}
	var resp _Irpc_outsideTestaddUint8Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate the code
	}
	return resp.Param0
}

type _Irpc_outsideTestaddUint8Req struct {
	Param0_a out.Uint8
	Param0_b out.Uint8
}

func (s _Irpc_outsideTestaddUint8Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.Param0_a)); err != nil {
		return fmt.Errorf("serialize s.Param0_a of type 'uint8': %w", err)
	}
	if err := e.Uint8(uint8(s.Param0_b)); err != nil {
		return fmt.Errorf("serialize s.Param0_b of type 'uint8': %w", err)
	}
	return nil
}
func (s *_Irpc_outsideTestaddUint8Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.Param0_a)); err != nil {
		return fmt.Errorf("deserialize s.Param0_a of type 'uint8': %w", err)
	}
	if err := d.Uint8((*uint8)(&s.Param0_b)); err != nil {
		return fmt.Errorf("deserialize s.Param0_b of type 'uint8': %w", err)
	}
	return nil
}

type _Irpc_outsideTestaddUint8Resp struct {
	Param0 out.Uint8
}

func (s _Irpc_outsideTestaddUint8Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.Param0)); err != nil {
		return fmt.Errorf("serialize s.Param0 of type 'uint8': %w", err)
	}
	return nil
}
func (s *_Irpc_outsideTestaddUint8Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.Param0)); err != nil {
		return fmt.Errorf("deserialize s.Param0 of type 'uint8': %w", err)
	}
	return nil
}
