// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/cmd/irpc/test/out"
	out1 "github.com/marben/irpc/cmd/irpc/test/out"
	out2 "github.com/marben/irpc/cmd/irpc/test/out"
	"github.com/marben/irpc/irpcgen"
)

type outsidepkgaliasIrpcService struct {
	impl outsidepkgalias
	id   []byte
}

func newOutsidepkgaliasIrpcService(impl outsidepkgalias) *outsidepkgaliasIrpcService {
	return &outsidepkgaliasIrpcService{
		impl: impl,
		id: []byte{
			0xac, 0x59, 0xe8, 0xd3, 0xb4, 0xd4, 0xa9, 0x24,
			0x70, 0xf3, 0xa1, 0x22, 0xb1, 0xf2, 0x50, 0x89,
			0xdd, 0x14, 0x85, 0x8d, 0x35, 0xd6, 0x52, 0xc4,
			0xd7, 0x86, 0x33, 0x68, 0x4a, 0xb9, 0x5a, 0xa7,
		},
	}
}
func (s *outsidepkgaliasIrpcService) Id() []byte {
	return s.id
}
func (s *outsidepkgaliasIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // add
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_addReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_addResp
				resp.p0 = s.impl.add(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 1: // add2
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_add2Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_add2Resp
				resp.p0 = s.impl.add2(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 2: // add3
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_add3Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_add3Resp
				resp.p0 = s.impl.add3(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 3: // sum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_sumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_sumResp
				resp.p0 = s.impl.sum(args.inSlice)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// outsidepkgaliasIrpcClient implements outsidepkgalias
type outsidepkgaliasIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newOutsidepkgaliasIrpcClient(endpoint irpcgen.Endpoint) (*outsidepkgaliasIrpcClient, error) {
	id := []byte{
		0xac, 0x59, 0xe8, 0xd3, 0xb4, 0xd4, 0xa9, 0x24,
		0x70, 0xf3, 0xa1, 0x22, 0xb1, 0xf2, 0x50, 0x89,
		0xdd, 0x14, 0x85, 0x8d, 0x35, 0xd6, 0x52, 0xc4,
		0xd7, 0x86, 0x33, 0x68, 0x4a, 0xb9, 0x5a, 0xa7,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &outsidepkgaliasIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *outsidepkgaliasIrpcClient) add(a out1.Uint8, b out1.Uint8) int {
	var req = _irpc_outsidepkgalias_addReq{
		a: a,
		b: b,
	}
	var resp _irpc_outsidepkgalias_addResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *outsidepkgaliasIrpcClient) add2(a out1.Uint8, b out.Uint8) int {
	var req = _irpc_outsidepkgalias_add2Req{
		a: a,
		b: b,
	}
	var resp _irpc_outsidepkgalias_add2Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *outsidepkgaliasIrpcClient) add3(a int, b out.Uint8) out2.Uint8 {
	var req = _irpc_outsidepkgalias_add3Req{
		a: a,
		b: b,
	}
	var resp _irpc_outsidepkgalias_add3Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *outsidepkgaliasIrpcClient) sum(inSlice out1.AliasedByteSlice) int {
	var req = _irpc_outsidepkgalias_sumReq{
		inSlice: inSlice,
	}
	var resp _irpc_outsidepkgalias_sumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_outsidepkgalias_addReq struct {
	a out1.Uint8
	b out1.Uint8
}

func (s _irpc_outsidepkgalias_addReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.a)); err != nil {
		return fmt.Errorf("serialize s.a of type \"out1.Uint8\": %w", err)
	}
	if err := e.Uint8(uint8(s.b)); err != nil {
		return fmt.Errorf("serialize s.b of type \"out1.Uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_addReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.a)); err != nil {
		return fmt.Errorf("deserialize s.a of type \"out1.Uint8\": %w", err)
	}
	if err := d.Uint8((*uint8)(&s.b)); err != nil {
		return fmt.Errorf("deserialize s.b of type \"out1.Uint8\": %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_addResp struct {
	p0 int
}

func (s _irpc_outsidepkgalias_addResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_addResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add2Req struct {
	a out1.Uint8
	b out.Uint8
}

func (s _irpc_outsidepkgalias_add2Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.a)); err != nil {
		return fmt.Errorf("serialize s.a of type \"out1.Uint8\": %w", err)
	}
	if err := e.Uint8(uint8(s.b)); err != nil {
		return fmt.Errorf("serialize s.b of type \"out.Uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add2Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.a)); err != nil {
		return fmt.Errorf("deserialize s.a of type \"out1.Uint8\": %w", err)
	}
	if err := d.Uint8((*uint8)(&s.b)); err != nil {
		return fmt.Errorf("deserialize s.b of type \"out.Uint8\": %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add2Resp struct {
	p0 int
}

func (s _irpc_outsidepkgalias_add2Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add2Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add3Req struct {
	a int
	b out.Uint8
}

func (s _irpc_outsidepkgalias_add3Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int\": %w", err)
	}
	if err := e.Uint8(uint8(s.b)); err != nil {
		return fmt.Errorf("serialize s.b of type \"out.Uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add3Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int\": %w", err)
	}
	if err := d.Uint8((*uint8)(&s.b)); err != nil {
		return fmt.Errorf("deserialize s.b of type \"out.Uint8\": %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add3Resp struct {
	p0 out2.Uint8
}

func (s _irpc_outsidepkgalias_add3Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.p0)); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"out2.Uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add3Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.p0)); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"out2.Uint8\": %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_sumReq struct {
	inSlice out1.AliasedByteSlice
}

func (s _irpc_outsidepkgalias_sumReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.inSlice out1.AliasedByteSlice
		if err := e.Len(len(s.inSlice)); err != nil {
			return fmt.Errorf("serialize len(s.inSlice) of type \"int\": %w", err)
		}
		for _, v := range s.inSlice {
			if err := e.Uint8(uint8(v)); err != nil {
				return fmt.Errorf("serialize v of type \"out_.Uint8\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_outsidepkgalias_sumReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.inSlice out1.AliasedByteSlice
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.inSlice = make(out1.AliasedByteSlice, l)
		for i := range l {
			if err := d.Uint8((*uint8)(&s.inSlice[i])); err != nil {
				return fmt.Errorf("deserialize s.inSlice[i] of type \"out_.Uint8\": %w", err)
			}
		}
	}
	return nil
}

type _irpc_outsidepkgalias_sumResp struct {
	p0 int
}

func (s _irpc_outsidepkgalias_sumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_sumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
