// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/outsidepkgalias.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/cmd/irpc/test/out"
	out1 "github.com/marben/irpc/cmd/irpc/test/out"
	out2 "github.com/marben/irpc/cmd/irpc/test/out"
	"github.com/marben/irpc/irpcgen"
)

var _outsidepkgaliasIrpcId = []byte{
	0x62, 0x14, 0x75, 0xf3, 0x3d, 0x3c, 0x77, 0x36,
	0xba, 0xb0, 0x36, 0x9b, 0xd7, 0x3b, 0xf7, 0x97,
	0xeb, 0x6e, 0xd6, 0xce, 0x0b, 0x5e, 0xd7, 0x58,
	0xe4, 0x0b, 0xd8, 0x36, 0xdc, 0x2e, 0x90, 0xe2,
}

type outsidepkgaliasIrpcService struct {
	impl outsidepkgalias
}

func newOutsidepkgaliasIrpcService(impl outsidepkgalias) *outsidepkgaliasIrpcService {
	return &outsidepkgaliasIrpcService{
		impl: impl,
	}
}
func (s *outsidepkgaliasIrpcService) Id() []byte {
	return _outsidepkgaliasIrpcId
}
func (s *outsidepkgaliasIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // add
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_addReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_addResp
				resp.p0 = s.impl.add(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 1: // add2
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_add2Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_add2Resp
				resp.p0 = s.impl.add2(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 2: // add3
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_add3Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_add3Resp
				resp.p0 = s.impl.add3(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 3: // sum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_outsidepkgalias_sumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_outsidepkgalias_sumResp
				resp.p0 = s.impl.sum(args.inSlice)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// outsidepkgaliasIrpcClient implements outsidepkgalias
type outsidepkgaliasIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newOutsidepkgaliasIrpcClient(endpoint irpcgen.Endpoint) (*outsidepkgaliasIrpcClient, error) {
	if err := endpoint.RegisterClient(_outsidepkgaliasIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &outsidepkgaliasIrpcClient{endpoint: endpoint}, nil
}
func (_c *outsidepkgaliasIrpcClient) add(a out1.Uint8, b out1.Uint8) int {
	var req = _irpc_outsidepkgalias_addReq{
		a: a,
		b: b,
	}
	var resp _irpc_outsidepkgalias_addResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _outsidepkgaliasIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *outsidepkgaliasIrpcClient) add2(a out1.Uint8, b out.Uint8) int {
	var req = _irpc_outsidepkgalias_add2Req{
		a: a,
		b: b,
	}
	var resp _irpc_outsidepkgalias_add2Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _outsidepkgaliasIrpcId, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *outsidepkgaliasIrpcClient) add3(a int, b out.Uint8) out2.Uint8 {
	var req = _irpc_outsidepkgalias_add3Req{
		a: a,
		b: b,
	}
	var resp _irpc_outsidepkgalias_add3Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _outsidepkgaliasIrpcId, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *outsidepkgaliasIrpcClient) sum(inSlice out1.AliasedByteSlice) int {
	var req = _irpc_outsidepkgalias_sumReq{
		inSlice: inSlice,
	}
	var resp _irpc_outsidepkgalias_sumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _outsidepkgaliasIrpcId, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_outsidepkgalias_addReq struct {
	a out1.Uint8
	b out1.Uint8
}

func (s _irpc_outsidepkgalias_addReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncUint8(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type out1.Uint8: %w", err)
	}
	if err := irpcgen.EncUint8(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type out1.Uint8: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_addReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecUint8(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type out1.Uint8: %w", err)
	}
	if err := irpcgen.DecUint8(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type out1.Uint8: %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_addResp struct {
	p0 int
}

func (s _irpc_outsidepkgalias_addResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_addResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add2Req struct {
	a out1.Uint8
	b out.Uint8
}

func (s _irpc_outsidepkgalias_add2Req) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncUint8(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type out1.Uint8: %w", err)
	}
	if err := irpcgen.EncUint8(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type out.Uint8: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add2Req) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecUint8(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type out1.Uint8: %w", err)
	}
	if err := irpcgen.DecUint8(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type out.Uint8: %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add2Resp struct {
	p0 int
}

func (s _irpc_outsidepkgalias_add2Resp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add2Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add3Req struct {
	a int
	b out.Uint8
}

func (s _irpc_outsidepkgalias_add3Req) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type int: %w", err)
	}
	if err := irpcgen.EncUint8(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type out.Uint8: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add3Req) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type int: %w", err)
	}
	if err := irpcgen.DecUint8(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type out.Uint8: %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_add3Resp struct {
	p0 out2.Uint8
}

func (s _irpc_outsidepkgalias_add3Resp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncUint8(e, s.p0); err != nil {
		return fmt.Errorf("serialize type out2.Uint8: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_add3Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecUint8(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type out2.Uint8: %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_sumReq struct {
	inSlice out1.AliasedByteSlice
}

func (s _irpc_outsidepkgalias_sumReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, sl out1.AliasedByteSlice) error {
		return irpcgen.EncSlice(enc, "out_.Uint8", irpcgen.EncUint8, sl)
	}(e, s.inSlice); err != nil {
		return fmt.Errorf("serialize \"inSlice\" of type out1.AliasedByteSlice: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_sumReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, sl *out1.AliasedByteSlice) error {
		return irpcgen.DecSlice(dec, "out_.Uint8", irpcgen.DecUint8, sl)
	}(d, &s.inSlice); err != nil {
		return fmt.Errorf("deserialize inSlice of type out1.AliasedByteSlice: %w", err)
	}
	return nil
}

type _irpc_outsidepkgalias_sumResp struct {
	p0 int
}

func (s _irpc_outsidepkgalias_sumResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_outsidepkgalias_sumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}
