// Code generated by irpc (devel); DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/outsidepkg.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/cmd/irpc/test/out"
	"github.com/marben/irpc/irpcgen"
)

var _outsideTestIrpcId = []byte{
	0xfc, 0x32, 0x07, 0xab, 0xdd, 0x50, 0xa3, 0x13,
	0x87, 0x80, 0xd5, 0xb0, 0x1e, 0x23, 0x3f, 0xe4,
	0x07, 0xf5, 0x5c, 0x67, 0x96, 0x87, 0x82, 0xfd,
	0xde, 0x68, 0x75, 0x79, 0xc4, 0xae, 0xcf, 0x00,
}

// outsideTestIrpcService provides [outsideTest] interface over irpc
type outsideTestIrpcService struct {
	impl outsideTest
}

// newOutsideTestIrpcService returns new [irpcgen.Service] forwarding [outsideTest] network calls to impl
func newOutsideTestIrpcService(impl outsideTest) *outsideTestIrpcService {
	return &outsideTestIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *outsideTestIrpcService) Id() []byte {
	return _outsideTestIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *outsideTestIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // addUint8
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_outsideTest_addUint8Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_outsideTest_addUint8Resp
				resp.p0 = s.impl.addUint8(args.a, args.b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// outsideTestIrpcClient implements [outsideTest] interface. It by forwards calls over network to [outsideTestIrpcService] that provides the implementation.
type outsideTestIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newOutsideTestIrpcClient(endpoint irpcgen.Endpoint) (*outsideTestIrpcClient, error) {
	if err := endpoint.RegisterClient(_outsideTestIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &outsideTestIrpcClient{endpoint: endpoint}, nil
}

// addUint8 implements [outsideTest]
//
func (_c *outsideTestIrpcClient) addUint8(a out.Uint8, b out.Uint8) out.Uint8 {
	var req = _irpc_outsideTest_addUint8Req{
		a: a,
		b: b,
	}
	var resp _irpc_outsideTest_addUint8Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _outsideTestIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_outsideTest_addUint8Req struct {
	a out.Uint8
	b out.Uint8
}

func (s _irpc_outsideTest_addUint8Req) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncUint8(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type out.Uint8: %w", err)
	}
	if err := irpcgen.EncUint8(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type out.Uint8: %w", err)
	}
	return nil
}
func (s *_irpc_outsideTest_addUint8Req) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecUint8(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type out.Uint8: %w", err)
	}
	if err := irpcgen.DecUint8(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type out.Uint8: %w", err)
	}
	return nil
}

type _irpc_outsideTest_addUint8Resp struct {
	p0 out.Uint8
}

func (s _irpc_outsideTest_addUint8Resp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncUint8(e, s.p0); err != nil {
		return fmt.Errorf("serialize type out.Uint8: %w", err)
	}
	return nil
}
func (s *_irpc_outsideTest_addUint8Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecUint8(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type out.Uint8: %w", err)
	}
	return nil
}
