// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/pointer.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
	"image"
)

var _pointerTestIrpcId = []byte{
	0xe2, 0x88, 0x7c, 0x4b, 0xa9, 0xc0, 0x9e, 0x40,
	0x14, 0x7b, 0xf2, 0xe3, 0xd3, 0x46, 0xa3, 0x03,
	0x1e, 0x40, 0x7e, 0x3a, 0x60, 0x9c, 0x56, 0x12,
	0x85, 0xf0, 0x6e, 0xc8, 0x7e, 0xf0, 0x8b, 0xf1,
}

// pointerTestIrpcService provides [pointerTest] interface over irpc
type pointerTestIrpcService struct {
	impl pointerTest
}

// newPointerTestIrpcService returns new [irpcgen.Service] forwarding [pointerTest] network calls to impl
func newPointerTestIrpcService(impl pointerTest) *pointerTestIrpcService {
	return &pointerTestIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *pointerTestIrpcService) Id() []byte {
	return _pointerTestIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *pointerTestIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // getImage
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_pointerTest_getImageResp
				resp.p0 = s.impl.getImage()
				return resp
			}, nil
		}, nil
	case 1: // getNilImage
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_pointerTest_getNilImageResp
				resp.p0 = s.impl.getNilImage()
				return resp
			}, nil
		}, nil
	case 2: // isNil
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_pointerTest_isNilReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_pointerTest_isNilResp
				resp.p0 = s.impl.isNil(args.ptr)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// pointerTestIrpcClient implements [pointerTest] interface. It by forwards calls over network to [pointerTestIrpcService] that provides the implementation.
type pointerTestIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newPointerTestIrpcClient(endpoint irpcgen.Endpoint) (*pointerTestIrpcClient, error) {
	if err := endpoint.RegisterClient(_pointerTestIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &pointerTestIrpcClient{endpoint: endpoint}, nil
}

// getImage implements [pointerTest]
//
func (_c *pointerTestIrpcClient) getImage() *image.RGBA {
	var resp _irpc_pointerTest_getImageResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _pointerTestIrpcId, 0, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// getNilImage implements [pointerTest]
func (_c *pointerTestIrpcClient) getNilImage() *image.RGBA {
	var resp _irpc_pointerTest_getNilImageResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _pointerTestIrpcId, 1, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// isNil implements [pointerTest]
func (_c *pointerTestIrpcClient) isNil(ptr *int) bool {
	var req = _irpc_pointerTest_isNilReq{
		ptr: ptr,
	}
	var resp _irpc_pointerTest_isNilResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _pointerTestIrpcId, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_pointerTest_getImageResp struct {
	p0 *image.RGBA
}

func (s _irpc_pointerTest_getImageResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, pt *image.RGBA) error {
		return irpcgen.EncPointer(enc, pt, "image.RGBA", func(enc *irpcgen.Encoder, s image.RGBA) error {
			if err := irpcgen.EncByteSlice(enc, s.Pix); err != nil {
				return fmt.Errorf("serialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Stride); err != nil {
				return fmt.Errorf("serialize s.Stride of type int: %w", err)
			}
			if err := func(enc *irpcgen.Encoder, s image.Rectangle) error {
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Min); err != nil {
					return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
				}
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Max); err != nil {
					return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(enc, s.Rect); err != nil {
				return fmt.Errorf("serialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type *image.RGBA: %w", err)
	}
	return nil
}
func (s *_irpc_pointerTest_getImageResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, pt **image.RGBA) error {
		return irpcgen.DecPointer(dec, pt, "image.RGBA", func(dec *irpcgen.Decoder, s *image.RGBA) error {
			if err := irpcgen.DecByteSlice(dec, &s.Pix); err != nil {
				return fmt.Errorf("deserialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Stride); err != nil {
				return fmt.Errorf("deserialize s.Stride of type int: %w", err)
			}
			if err := func(dec *irpcgen.Decoder, s *image.Rectangle) error {
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Min); err != nil {
					return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
				}
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Max); err != nil {
					return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(dec, &s.Rect); err != nil {
				return fmt.Errorf("deserialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type *image.RGBA: %w", err)
	}
	return nil
}

type _irpc_pointerTest_getNilImageResp struct {
	p0 *image.RGBA
}

func (s _irpc_pointerTest_getNilImageResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, pt *image.RGBA) error {
		return irpcgen.EncPointer(enc, pt, "image.RGBA", func(enc *irpcgen.Encoder, s image.RGBA) error {
			if err := irpcgen.EncByteSlice(enc, s.Pix); err != nil {
				return fmt.Errorf("serialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.EncInt(enc, s.Stride); err != nil {
				return fmt.Errorf("serialize s.Stride of type int: %w", err)
			}
			if err := func(enc *irpcgen.Encoder, s image.Rectangle) error {
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Min); err != nil {
					return fmt.Errorf("serialize s.Min of type image.Point: %w", err)
				}
				if err := func(enc *irpcgen.Encoder, s image.Point) error {
					if err := irpcgen.EncInt(enc, s.X); err != nil {
						return fmt.Errorf("serialize s.X of type int: %w", err)
					}
					if err := irpcgen.EncInt(enc, s.Y); err != nil {
						return fmt.Errorf("serialize s.Y of type int: %w", err)
					}
					return nil
				}(enc, s.Max); err != nil {
					return fmt.Errorf("serialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(enc, s.Rect); err != nil {
				return fmt.Errorf("serialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type *image.RGBA: %w", err)
	}
	return nil
}
func (s *_irpc_pointerTest_getNilImageResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, pt **image.RGBA) error {
		return irpcgen.DecPointer(dec, pt, "image.RGBA", func(dec *irpcgen.Decoder, s *image.RGBA) error {
			if err := irpcgen.DecByteSlice(dec, &s.Pix); err != nil {
				return fmt.Errorf("deserialize s.Pix of type []uint8: %w", err)
			}
			if err := irpcgen.DecInt(dec, &s.Stride); err != nil {
				return fmt.Errorf("deserialize s.Stride of type int: %w", err)
			}
			if err := func(dec *irpcgen.Decoder, s *image.Rectangle) error {
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Min); err != nil {
					return fmt.Errorf("deserialize s.Min of type image.Point: %w", err)
				}
				if err := func(dec *irpcgen.Decoder, s *image.Point) error {
					if err := irpcgen.DecInt(dec, &s.X); err != nil {
						return fmt.Errorf("deserialize s.X of type int: %w", err)
					}
					if err := irpcgen.DecInt(dec, &s.Y); err != nil {
						return fmt.Errorf("deserialize s.Y of type int: %w", err)
					}
					return nil
				}(dec, &s.Max); err != nil {
					return fmt.Errorf("deserialize s.Max of type image.Point: %w", err)
				}
				return nil
			}(dec, &s.Rect); err != nil {
				return fmt.Errorf("deserialize s.Rect of type image.Rectangle: %w", err)
			}
			return nil
		})
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type *image.RGBA: %w", err)
	}
	return nil
}

type _irpc_pointerTest_isNilReq struct {
	ptr *int
}

func (s _irpc_pointerTest_isNilReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, pt *int) error {
		return irpcgen.EncPointer(enc, pt, "int", irpcgen.EncInt)
	}(e, s.ptr); err != nil {
		return fmt.Errorf("serialize \"ptr\" of type *int: %w", err)
	}
	return nil
}
func (s *_irpc_pointerTest_isNilReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, pt **int) error {
		return irpcgen.DecPointer(dec, pt, "int", irpcgen.DecInt)
	}(d, &s.ptr); err != nil {
		return fmt.Errorf("deserialize ptr of type *int: %w", err)
	}
	return nil
}

type _irpc_pointerTest_isNilResp struct {
	p0 bool
}

func (s _irpc_pointerTest_isNilResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncBool(e, s.p0); err != nil {
		return fmt.Errorf("serialize type bool: %w", err)
	}
	return nil
}
func (s *_irpc_pointerTest_isNilResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecBool(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type bool: %w", err)
	}
	return nil
}
