// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/cmd/irpc/test/out"
	"github.com/marben/irpc/irpcgen"
)

type sliceNamedApiIrpcService struct {
	impl sliceNamedApi
	id   []byte
}

func newSliceNamedApiIrpcService(impl sliceNamedApi) *sliceNamedApiIrpcService {
	return &sliceNamedApiIrpcService{
		impl: impl,
		id: []byte{
			0xb6, 0x3d, 0x02, 0xba, 0xbc, 0x45, 0xad, 0x2d,
			0x33, 0xda, 0x05, 0x04, 0xa0, 0x07, 0x3d, 0x05,
			0xd8, 0x91, 0xe3, 0xab, 0xc7, 0x1b, 0x3b, 0x43,
			0xb0, 0xe5, 0x7d, 0xd2, 0x1b, 0x93, 0x5c, 0xde,
		},
	}
}
func (s *sliceNamedApiIrpcService) Id() []byte {
	return s.id
}
func (s *sliceNamedApiIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // sumNamedInts
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_sliceNamedApisumNamedIntsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _Irpc_sliceNamedApisumNamedIntsResp
				resp.Param0 = s.impl.sumNamedInts(args.Param0_vec)
				return resp
			}, nil
		}, nil
	case 1: // sumOutsideNamedInts
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_sliceNamedApisumOutsideNamedIntsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _Irpc_sliceNamedApisumOutsideNamedIntsResp
				resp.Param0 = s.impl.sumOutsideNamedInts(args.Param0_vec)
				return resp
			}, nil
		}, nil
	case 2: // sumSliceOfNamedInts
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_sliceNamedApisumSliceOfNamedIntsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _Irpc_sliceNamedApisumSliceOfNamedIntsResp
				resp.Param0 = s.impl.sumSliceOfNamedInts(args.Param0_vec)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

type sliceNamedApiIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newSliceNamedApiIrpcClient(endpoint irpcgen.Endpoint) (*sliceNamedApiIrpcClient, error) {
	id := []byte{
		0xb6, 0x3d, 0x02, 0xba, 0xbc, 0x45, 0xad, 0x2d,
		0x33, 0xda, 0x05, 0x04, 0xa0, 0x07, 0x3d, 0x05,
		0xd8, 0x91, 0xe3, 0xab, 0xc7, 0x1b, 0x3b, 0x43,
		0xb0, 0xe5, 0x7d, 0xd2, 0x1b, 0x93, 0x5c, 0xde,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &sliceNamedApiIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *sliceNamedApiIrpcClient) sumNamedInts(vec namedSliceOfInts) int {
	var req = _Irpc_sliceNamedApisumNamedIntsReq{
		Param0_vec: vec,
	}
	var resp _Irpc_sliceNamedApisumNamedIntsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.Param0
}
func (_c *sliceNamedApiIrpcClient) sumOutsideNamedInts(vec out.AliasedByteSlice) int {
	var req = _Irpc_sliceNamedApisumOutsideNamedIntsReq{
		Param0_vec: vec,
	}
	var resp _Irpc_sliceNamedApisumOutsideNamedIntsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.Param0
}
func (_c *sliceNamedApiIrpcClient) sumSliceOfNamedInts(vec []out.Uint8) out.Uint8 {
	var req = _Irpc_sliceNamedApisumSliceOfNamedIntsReq{
		Param0_vec: vec,
	}
	var resp _Irpc_sliceNamedApisumSliceOfNamedIntsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.Param0
}

type _Irpc_sliceNamedApisumNamedIntsReq struct {
	Param0_vec namedSliceOfInts
}

func (s _Irpc_sliceNamedApisumNamedIntsReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.Param0_vec namedSliceOfInts
		if err := e.Len(len(s.Param0_vec)); err != nil {
			return fmt.Errorf("serialize len(s.Param0_vec) of type \"int\": %w", err)
		}
		for _, v := range s.Param0_vec {
			if err := e.VarInt(v); err != nil {
				return fmt.Errorf("serialize v of type \"int\": %w", err)
			}
		}
	}
	return nil
}
func (s *_Irpc_sliceNamedApisumNamedIntsReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.Param0_vec namedSliceOfInts
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.Param0_vec = make(namedSliceOfInts, l)
		for i := range l {
			if err := d.VarInt(&s.Param0_vec[i]); err != nil {
				return fmt.Errorf("deserialize s.Param0_vec[i] of type \"int\": %w", err)
			}
		}
	}
	return nil
}

type _Irpc_sliceNamedApisumNamedIntsResp struct {
	Param0 int
}

func (s _Irpc_sliceNamedApisumNamedIntsResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0); err != nil {
		return fmt.Errorf("serialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_sliceNamedApisumNamedIntsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0); err != nil {
		return fmt.Errorf("deserialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}

type _Irpc_sliceNamedApisumOutsideNamedIntsReq struct {
	Param0_vec out.AliasedByteSlice
}

func (s _Irpc_sliceNamedApisumOutsideNamedIntsReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.Param0_vec out.AliasedByteSlice
		if err := e.Len(len(s.Param0_vec)); err != nil {
			return fmt.Errorf("serialize len(s.Param0_vec) of type \"int\": %w", err)
		}
		for _, v := range s.Param0_vec {
			if err := e.Uint8(uint8(v)); err != nil {
				return fmt.Errorf("serialize v of type \"out_.Uint8\": %w", err)
			}
		}
	}
	return nil
}
func (s *_Irpc_sliceNamedApisumOutsideNamedIntsReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.Param0_vec out.AliasedByteSlice
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.Param0_vec = make(out.AliasedByteSlice, l)
		for i := range l {
			if err := d.Uint8((*uint8)(&s.Param0_vec[i])); err != nil {
				return fmt.Errorf("deserialize s.Param0_vec[i] of type \"out_.Uint8\": %w", err)
			}
		}
	}
	return nil
}

type _Irpc_sliceNamedApisumOutsideNamedIntsResp struct {
	Param0 int
}

func (s _Irpc_sliceNamedApisumOutsideNamedIntsResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.Param0); err != nil {
		return fmt.Errorf("serialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_Irpc_sliceNamedApisumOutsideNamedIntsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.Param0); err != nil {
		return fmt.Errorf("deserialize s.Param0 of type \"int\": %w", err)
	}
	return nil
}

type _Irpc_sliceNamedApisumSliceOfNamedIntsReq struct {
	Param0_vec []out.Uint8
}

func (s _Irpc_sliceNamedApisumSliceOfNamedIntsReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.Param0_vec []out.Uint8
		if err := e.Len(len(s.Param0_vec)); err != nil {
			return fmt.Errorf("serialize len(s.Param0_vec) of type \"int\": %w", err)
		}
		for _, v := range s.Param0_vec {
			if err := e.Uint8(uint8(v)); err != nil {
				return fmt.Errorf("serialize v of type \"out.Uint8\": %w", err)
			}
		}
	}
	return nil
}
func (s *_Irpc_sliceNamedApisumSliceOfNamedIntsReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.Param0_vec []out.Uint8
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.Param0_vec = make([]out.Uint8, l)
		for i := range l {
			if err := d.Uint8((*uint8)(&s.Param0_vec[i])); err != nil {
				return fmt.Errorf("deserialize s.Param0_vec[i] of type \"out.Uint8\": %w", err)
			}
		}
	}
	return nil
}

type _Irpc_sliceNamedApisumSliceOfNamedIntsResp struct {
	Param0 out.Uint8
}

func (s _Irpc_sliceNamedApisumSliceOfNamedIntsResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Uint8(uint8(s.Param0)); err != nil {
		return fmt.Errorf("serialize s.Param0 of type \"out.Uint8\": %w", err)
	}
	return nil
}
func (s *_Irpc_sliceNamedApisumSliceOfNamedIntsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Uint8((*uint8)(&s.Param0)); err != nil {
		return fmt.Errorf("deserialize s.Param0 of type \"out.Uint8\": %w", err)
	}
	return nil
}
