// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/slice.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _sliceTestIrpcId = []byte{
	0x03, 0x4e, 0x6c, 0x87, 0xd2, 0x60, 0x86, 0x66,
	0x6e, 0xf1, 0x44, 0xd9, 0x42, 0x19, 0x0f, 0xb9,
	0x1f, 0xba, 0xbf, 0x71, 0x06, 0x82, 0x2a, 0x9a,
	0xe8, 0x12, 0xc9, 0x76, 0xbc, 0x85, 0xbf, 0xe0,
}

type sliceTestIrpcService struct {
	impl sliceTest
}

func newSliceTestIrpcService(impl sliceTest) *sliceTestIrpcService {
	return &sliceTestIrpcService{
		impl: impl,
	}
}
func (s *sliceTestIrpcService) Id() []byte {
	return _sliceTestIrpcId
}
func (s *sliceTestIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // SliceSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_SliceSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_SliceSumResp
				resp.p0 = s.impl.SliceSum(args.slice)
				return resp
			}, nil
		}, nil
	case 1: // VectMult
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_VectMultReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_VectMultResp
				resp.p0 = s.impl.VectMult(args.vect, args.s)
				return resp
			}, nil
		}, nil
	case 2: // SliceOfFloat64Sum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_SliceOfFloat64SumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_SliceOfFloat64SumResp
				resp.p0 = s.impl.SliceOfFloat64Sum(args.slice)
				return resp
			}, nil
		}, nil
	case 3: // SliceOfSlicesSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_SliceOfSlicesSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_SliceOfSlicesSumResp
				resp.p0 = s.impl.SliceOfSlicesSum(args.slice)
				return resp
			}, nil
		}, nil
	case 4: // SliceOfBytesSum
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_SliceOfBytesSumReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_SliceOfBytesSumResp
				resp.p0 = s.impl.SliceOfBytesSum(args.slice)
				return resp
			}, nil
		}, nil
	case 5: // namedByteSlice
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_namedByteSliceReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_namedByteSliceResp
				resp.p0 = s.impl.namedByteSlice(args.slice)
				return resp
			}, nil
		}, nil
	case 6: // sliceOfBools
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_sliceOfBoolsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_sliceOfBoolsResp
				resp.p0 = s.impl.sliceOfBools(args.slice)
				return resp
			}, nil
		}, nil
	case 7: // sliceOfUint8
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_sliceOfUint8Req
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_sliceTest_sliceOfUint8Resp
				resp.p0 = s.impl.sliceOfUint8(args.slice)
				return resp
			}, nil
		}, nil
	case 8: // sliceOfErrors
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_sliceTest_sliceOfErrorsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				s.impl.sliceOfErrors(args.slice)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// sliceTestIrpcClient implements sliceTest
type sliceTestIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newSliceTestIrpcClient(endpoint irpcgen.Endpoint) (*sliceTestIrpcClient, error) {
	if err := endpoint.RegisterClient(_sliceTestIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &sliceTestIrpcClient{endpoint: endpoint}, nil
}
func (_c *sliceTestIrpcClient) SliceSum(slice []int) int {
	var req = _irpc_sliceTest_SliceSumReq{
		slice: slice,
	}
	var resp _irpc_sliceTest_SliceSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) VectMult(vect []int, s int) []int {
	var req = _irpc_sliceTest_VectMultReq{
		vect: vect,
		s:    s,
	}
	var resp _irpc_sliceTest_VectMultResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 1, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) SliceOfFloat64Sum(slice []float64) float64 {
	var req = _irpc_sliceTest_SliceOfFloat64SumReq{
		slice: slice,
	}
	var resp _irpc_sliceTest_SliceOfFloat64SumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 2, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) SliceOfSlicesSum(slice [][]int) int {
	var req = _irpc_sliceTest_SliceOfSlicesSumReq{
		slice: slice,
	}
	var resp _irpc_sliceTest_SliceOfSlicesSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 3, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) SliceOfBytesSum(slice []byte) int {
	var req = _irpc_sliceTest_SliceOfBytesSumReq{
		slice: slice,
	}
	var resp _irpc_sliceTest_SliceOfBytesSumResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 4, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) namedByteSlice(slice namedByteSlice) int {
	var req = _irpc_sliceTest_namedByteSliceReq{
		slice: slice,
	}
	var resp _irpc_sliceTest_namedByteSliceResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 5, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) sliceOfBools(slice []bool) namedBoolSlice {
	var req = _irpc_sliceTest_sliceOfBoolsReq{
		slice: slice,
	}
	var resp _irpc_sliceTest_sliceOfBoolsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 6, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) sliceOfUint8(slice []uint8) []byte {
	var req = _irpc_sliceTest_sliceOfUint8Req{
		slice: slice,
	}
	var resp _irpc_sliceTest_sliceOfUint8Resp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 7, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *sliceTestIrpcClient) sliceOfErrors(slice []error) {
	var req = _irpc_sliceTest_sliceOfErrorsReq{
		slice: slice,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _sliceTestIrpcId, 8, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

type _irpc_sliceTest_SliceSumReq struct {
	slice []int
}

func (s _irpc_sliceTest_SliceSumReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.slice []int
		if err := e.Len(len(s.slice)); err != nil {
			return fmt.Errorf("serialize len(s.slice) of type \"int\": %w", err)
		}
		for _, v := range s.slice {
			if err := e.VarInt(v); err != nil {
				return fmt.Errorf("serialize v of type \"int\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_sliceTest_SliceSumReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.slice []int
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.slice = make([]int, l)
		for i := range l {
			if err := d.VarInt(&s.slice[i]); err != nil {
				return fmt.Errorf("deserialize s.slice[i] of type \"int\": %w", err)
			}
		}
	}
	return nil
}

type _irpc_sliceTest_SliceSumResp struct {
	p0 int
}

func (s _irpc_sliceTest_SliceSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_SliceSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_VectMultReq struct {
	vect []int
	s    int
}

func (s _irpc_sliceTest_VectMultReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.vect []int
		if err := e.Len(len(s.vect)); err != nil {
			return fmt.Errorf("serialize len(s.vect) of type \"int\": %w", err)
		}
		for _, v := range s.vect {
			if err := e.VarInt(v); err != nil {
				return fmt.Errorf("serialize v of type \"int\": %w", err)
			}
		}
	}
	if err := e.VarInt(s.s); err != nil {
		return fmt.Errorf("serialize s.s of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_VectMultReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.vect []int
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.vect = make([]int, l)
		for i := range l {
			if err := d.VarInt(&s.vect[i]); err != nil {
				return fmt.Errorf("deserialize s.vect[i] of type \"int\": %w", err)
			}
		}
	}
	if err := d.VarInt(&s.s); err != nil {
		return fmt.Errorf("deserialize s.s of type \"int\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_VectMultResp struct {
	p0 []int
}

func (s _irpc_sliceTest_VectMultResp) Serialize(e *irpcgen.Encoder) error {
	{ // s.p0 []int
		if err := e.Len(len(s.p0)); err != nil {
			return fmt.Errorf("serialize len(s.p0) of type \"int\": %w", err)
		}
		for _, v := range s.p0 {
			if err := e.VarInt(v); err != nil {
				return fmt.Errorf("serialize v of type \"int\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_sliceTest_VectMultResp) Deserialize(d *irpcgen.Decoder) error {
	{ // s.p0 []int
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.p0 = make([]int, l)
		for i := range l {
			if err := d.VarInt(&s.p0[i]); err != nil {
				return fmt.Errorf("deserialize s.p0[i] of type \"int\": %w", err)
			}
		}
	}
	return nil
}

type _irpc_sliceTest_SliceOfFloat64SumReq struct {
	slice []float64
}

func (s _irpc_sliceTest_SliceOfFloat64SumReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.slice []float64
		if err := e.Len(len(s.slice)); err != nil {
			return fmt.Errorf("serialize len(s.slice) of type \"int\": %w", err)
		}
		for _, v := range s.slice {
			if err := e.Float64le(v); err != nil {
				return fmt.Errorf("serialize v of type \"float64\": %w", err)
			}
		}
	}
	return nil
}
func (s *_irpc_sliceTest_SliceOfFloat64SumReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.slice []float64
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.slice = make([]float64, l)
		for i := range l {
			if err := d.Float64le(&s.slice[i]); err != nil {
				return fmt.Errorf("deserialize s.slice[i] of type \"float64\": %w", err)
			}
		}
	}
	return nil
}

type _irpc_sliceTest_SliceOfFloat64SumResp struct {
	p0 float64
}

func (s _irpc_sliceTest_SliceOfFloat64SumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"float64\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_SliceOfFloat64SumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"float64\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_SliceOfSlicesSumReq struct {
	slice [][]int
}

func (s _irpc_sliceTest_SliceOfSlicesSumReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.slice [][]int
		if err := e.Len(len(s.slice)); err != nil {
			return fmt.Errorf("serialize len(s.slice) of type \"int\": %w", err)
		}
		for _, v := range s.slice {
			{ // v []int
				if err := e.Len(len(v)); err != nil {
					return fmt.Errorf("serialize len(v) of type \"int\": %w", err)
				}
				for _, v := range v {
					if err := e.VarInt(v); err != nil {
						return fmt.Errorf("serialize v of type \"int\": %w", err)
					}
				}
			}
		}
	}
	return nil
}
func (s *_irpc_sliceTest_SliceOfSlicesSumReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.slice [][]int
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.slice = make([][]int, l)
		for i := range l {
			{ // s.slice[i] []int
				var l int
				if err := d.Len(&l); err != nil {
					return fmt.Errorf("deserialize l of type \"int\": %w", err)
				}
				s.slice[i] = make([]int, l)
				for j := range l {
					if err := d.VarInt(&s.slice[i][j]); err != nil {
						return fmt.Errorf("deserialize s.slice[i][j] of type \"int\": %w", err)
					}
				}
			}
		}
	}
	return nil
}

type _irpc_sliceTest_SliceOfSlicesSumResp struct {
	p0 int
}

func (s _irpc_sliceTest_SliceOfSlicesSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_SliceOfSlicesSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_SliceOfBytesSumReq struct {
	slice []byte
}

func (s _irpc_sliceTest_SliceOfBytesSumReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.ByteSlice(s.slice); err != nil {
		return fmt.Errorf("serialize s.slice of type \"[]byte\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_SliceOfBytesSumReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.ByteSlice(&s.slice); err != nil {
		return fmt.Errorf("deserialize s.slice of type \"[]byte\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_SliceOfBytesSumResp struct {
	p0 int
}

func (s _irpc_sliceTest_SliceOfBytesSumResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_SliceOfBytesSumResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_namedByteSliceReq struct {
	slice namedByteSlice
}

func (s _irpc_sliceTest_namedByteSliceReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.ByteSlice([]byte(s.slice)); err != nil {
		return fmt.Errorf("serialize s.slice of type \"namedByteSlice\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_namedByteSliceReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.ByteSlice((*[]byte)(&s.slice)); err != nil {
		return fmt.Errorf("deserialize s.slice of type \"namedByteSlice\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_namedByteSliceResp struct {
	p0 int
}

func (s _irpc_sliceTest_namedByteSliceResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_namedByteSliceResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_sliceOfBoolsReq struct {
	slice []bool
}

func (s _irpc_sliceTest_sliceOfBoolsReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.BoolSlice(s.slice); err != nil {
		return fmt.Errorf("serialize s.slice of type \"[]bool\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_sliceOfBoolsReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.BoolSlice(&s.slice); err != nil {
		return fmt.Errorf("deserialize s.slice of type \"[]bool\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_sliceOfBoolsResp struct {
	p0 namedBoolSlice
}

func (s _irpc_sliceTest_sliceOfBoolsResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.BoolSlice([]bool(s.p0)); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"namedBoolSlice\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_sliceOfBoolsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.BoolSlice((*[]bool)(&s.p0)); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"namedBoolSlice\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_sliceOfUint8Req struct {
	slice []uint8
}

func (s _irpc_sliceTest_sliceOfUint8Req) Serialize(e *irpcgen.Encoder) error {
	if err := e.ByteSlice(s.slice); err != nil {
		return fmt.Errorf("serialize s.slice of type \"[]uint8\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_sliceOfUint8Req) Deserialize(d *irpcgen.Decoder) error {
	if err := d.ByteSlice(&s.slice); err != nil {
		return fmt.Errorf("deserialize s.slice of type \"[]uint8\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_sliceOfUint8Resp struct {
	p0 []byte
}

func (s _irpc_sliceTest_sliceOfUint8Resp) Serialize(e *irpcgen.Encoder) error {
	if err := e.ByteSlice(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"[]byte\": %w", err)
	}
	return nil
}
func (s *_irpc_sliceTest_sliceOfUint8Resp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.ByteSlice(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"[]byte\": %w", err)
	}
	return nil
}

type _irpc_sliceTest_sliceOfErrorsReq struct {
	slice []error
}

func (s _irpc_sliceTest_sliceOfErrorsReq) Serialize(e *irpcgen.Encoder) error {
	{ // s.slice []error
		if err := e.Len(len(s.slice)); err != nil {
			return fmt.Errorf("serialize len(s.slice) of type \"int\": %w", err)
		}
		for _, v := range s.slice {
			{
				var isNil bool
				if v == nil {
					isNil = true
				}
				if err := e.Bool(isNil); err != nil {
					return fmt.Errorf("serialize isNil of type \"bool\": %w", err)
				}

				if !isNil {
					{ // Error()
						_Error_0_ := v.Error()
						if err := e.String(_Error_0_); err != nil {
							return fmt.Errorf("serialize _Error_0_ of type \"string\": %w", err)
						}
					}
				}
			}
		}
	}
	return nil
}
func (s *_irpc_sliceTest_sliceOfErrorsReq) Deserialize(d *irpcgen.Decoder) error {
	{ // s.slice []error
		var l int
		if err := d.Len(&l); err != nil {
			return fmt.Errorf("deserialize l of type \"int\": %w", err)
		}
		s.slice = make([]error, l)
		for i := range l {
			{
				var isNil bool
				if err := d.Bool(&isNil); err != nil {
					return fmt.Errorf("deserialize isNil of type \"bool\": %w", err)
				}

				if isNil {
					s.slice[i] = nil
				} else {
					var impl _error_sliceTest_impl
					{ // Error()
						if err := d.String(&impl._Error_0_); err != nil {
							return fmt.Errorf("deserialize impl._Error_0_ of type \"string\": %w", err)
						}
					}
					s.slice[i] = impl
				}
			}
		}
	}
	return nil
}

type _error_sliceTest_impl struct {
	_Error_0_ string
}

func (i _error_sliceTest_impl) Error() string {
	return i._Error_0_
}
