// Code generated by irpc generator; DO NOT EDIT
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type tcpTestApiIrpcService struct {
	impl tcpTestApi
	id   []byte
}

func newTcpTestApiIrpcService(impl tcpTestApi) *tcpTestApiIrpcService {
	return &tcpTestApiIrpcService{
		impl: impl,
		id: []byte{
			0x82, 0xe7, 0x92, 0xa2, 0xd8, 0xb5, 0x9c, 0xe3,
			0x44, 0x75, 0x3b, 0x88, 0x21, 0xe8, 0x65, 0x8f,
			0xef, 0x85, 0xdd, 0x6d, 0x0e, 0xb5, 0xb9, 0xec,
			0xcd, 0xec, 0x14, 0x01, 0xaa, 0x6f, 0x12, 0x1d,
		},
	}
}
func (s *tcpTestApiIrpcService) Id() []byte {
	return s.id
}
func (s *tcpTestApiIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // Div
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _Irpc_tcpTestApiDivReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _Irpc_tcpTestApiDivResp
				resp.Param0, resp.Param1 = s.impl.Div(args.Param0_a, args.Param0_b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

type tcpTestApiIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func newTcpTestApiIrpcClient(endpoint irpcgen.Endpoint) (*tcpTestApiIrpcClient, error) {
	id := []byte{
		0x82, 0xe7, 0x92, 0xa2, 0xd8, 0xb5, 0x9c, 0xe3,
		0x44, 0x75, 0x3b, 0x88, 0x21, 0xe8, 0x65, 0x8f,
		0xef, 0x85, 0xdd, 0x6d, 0x0e, 0xb5, 0xb9, 0xec,
		0xcd, 0xec, 0x14, 0x01, 0xaa, 0x6f, 0x12, 0x1d,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &tcpTestApiIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *tcpTestApiIrpcClient) Div(a float64, b float64) (float64, error) {
	var req = _Irpc_tcpTestApiDivReq{
		Param0_a: a,
		Param0_b: b,
	}
	var resp _Irpc_tcpTestApiDivResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		var zero _Irpc_tcpTestApiDivResp
		return zero.Param0, err
	}
	return resp.Param0, resp.Param1
}

type _Irpc_tcpTestApiDivReq struct {
	Param0_a float64
	Param0_b float64
}

func (s _Irpc_tcpTestApiDivReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(s.Param0_a); err != nil {
		return fmt.Errorf("serialize s.Param0_a of type \"float64\": %w", err)
	}
	if err := e.Float64le(s.Param0_b); err != nil {
		return fmt.Errorf("serialize s.Param0_b of type \"float64\": %w", err)
	}
	return nil
}
func (s *_Irpc_tcpTestApiDivReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le(&s.Param0_a); err != nil {
		return fmt.Errorf("deserialize s.Param0_a of type \"float64\": %w", err)
	}
	if err := d.Float64le(&s.Param0_b); err != nil {
		return fmt.Errorf("deserialize s.Param0_b of type \"float64\": %w", err)
	}
	return nil
}

type _Irpc_tcpTestApiDivResp struct {
	Param0 float64
	Param1 error
}

func (s _Irpc_tcpTestApiDivResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.Float64le(s.Param0); err != nil {
		return fmt.Errorf("serialize s.Param0 of type \"float64\": %w", err)
	}
	{
		var isNil bool
		if s.Param1 == nil {
			isNil = true
		}
		if err := e.Bool(isNil); err != nil {
			return fmt.Errorf("serialize isNil of type \"bool\": %w", err)
		}

		if !isNil {
			{ // Error()
				_Error_0_ := s.Param1.Error()
				if err := e.String(_Error_0_); err != nil {
					return fmt.Errorf("serialize _Error_0_ of type \"string\": %w", err)
				}
			}
		}
	}
	return nil
}
func (s *_Irpc_tcpTestApiDivResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.Float64le(&s.Param0); err != nil {
		return fmt.Errorf("deserialize s.Param0 of type \"float64\": %w", err)
	}
	{
		var isNil bool
		if err := d.Bool(&isNil); err != nil {
			return fmt.Errorf("deserialize isNil of type \"bool\": %w", err)
		}

		if isNil {
			s.Param1 = nil
		} else {
			var impl _error_tcpTestApi_impl
			{ // Error()
				if err := d.String(&impl._Error_0_); err != nil {
					return fmt.Errorf("deserialize impl._Error_0_ of type \"string\": %w", err)
				}
			}
			s.Param1 = impl
		}
	}
	return nil
}

type _error_tcpTestApi_impl struct {
	_Error_0_ string
}

func (i _error_tcpTestApi_impl) Error() string {
	return i._Error_0_
}
