// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/typeblock.go
package irpctestpkg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _tbInterfaceAIrpcId = []byte{
	0xa4, 0xa5, 0xf1, 0x00, 0xb5, 0x8c, 0x53, 0x02,
	0xfb, 0x27, 0x74, 0xeb, 0x50, 0xa3, 0xe7, 0x4a,
	0xdc, 0x25, 0x52, 0xf5, 0x3d, 0x51, 0x88, 0xce,
	0xc3, 0xf7, 0x57, 0x90, 0x44, 0x95, 0x4b, 0x1f,
}

// tbInterfaceAIrpcService provides [tbInterfaceA] interface over irpc
type tbInterfaceAIrpcService struct {
	impl tbInterfaceA
}

// newTbInterfaceAIrpcService returns new [irpcgen.Service] forwarding [tbInterfaceA] network calls to impl
func newTbInterfaceAIrpcService(impl tbInterfaceA) *tbInterfaceAIrpcService {
	return &tbInterfaceAIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *tbInterfaceAIrpcService) Id() []byte {
	return _tbInterfaceAIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *tbInterfaceAIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // reverse
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_tbInterfaceA_reverseReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_tbInterfaceA_reverseResp
				resp.p02 = s.impl.reverse(args.p0)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// tbInterfaceAIrpcClient implements [tbInterfaceA] interface. It by forwards calls over network to [tbInterfaceAIrpcService] that provides the implementation.
//
// tbInterfaceA deals with string
type tbInterfaceAIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newTbInterfaceAIrpcClient(endpoint irpcgen.Endpoint) (*tbInterfaceAIrpcClient, error) {
	if err := endpoint.RegisterClient(_tbInterfaceAIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &tbInterfaceAIrpcClient{endpoint: endpoint}, nil
}

// reverse implements [tbInterfaceA]
//
func (_c *tbInterfaceAIrpcClient) reverse(p0 string) string {
	var req = _irpc_tbInterfaceA_reverseReq{
		p0: p0,
	}
	var resp _irpc_tbInterfaceA_reverseResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _tbInterfaceAIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p02
}

type _irpc_tbInterfaceA_reverseReq struct {
	p0 string
}

func (s _irpc_tbInterfaceA_reverseReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p0); err != nil {
		return fmt.Errorf("serialize \"p0\" of type string: %w", err)
	}
	return nil
}
func (s *_irpc_tbInterfaceA_reverseReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize p0 of type string: %w", err)
	}
	return nil
}

type _irpc_tbInterfaceA_reverseResp struct {
	p02 string
}

func (s _irpc_tbInterfaceA_reverseResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncString(e, s.p02); err != nil {
		return fmt.Errorf("serialize type string: %w", err)
	}
	return nil
}
func (s *_irpc_tbInterfaceA_reverseResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecString(d, &s.p02); err != nil {
		return fmt.Errorf("deserialize type string: %w", err)
	}
	return nil
}

var _tvInterfaceBIrpcId = []byte{
	0xc1, 0x26, 0xca, 0x93, 0xba, 0x99, 0x24, 0x35,
	0xaf, 0xb7, 0x1a, 0x14, 0x80, 0xea, 0xea, 0xa1,
	0x04, 0xa3, 0x2a, 0x53, 0x35, 0x6d, 0xae, 0x73,
	0xa3, 0x19, 0x38, 0x22, 0x0d, 0x23, 0x8e, 0x6a,
}

// tvInterfaceBIrpcService provides [tvInterfaceB] interface over irpc
type tvInterfaceBIrpcService struct {
	impl tvInterfaceB
}

// newTvInterfaceBIrpcService returns new [irpcgen.Service] forwarding [tvInterfaceB] network calls to impl
func newTvInterfaceBIrpcService(impl tvInterfaceB) *tvInterfaceBIrpcService {
	return &tvInterfaceBIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *tvInterfaceBIrpcService) Id() []byte {
	return _tvInterfaceBIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *tvInterfaceBIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // add
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_tvInterfaceB_addReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_tvInterfaceB_addResp
				resp.p0 = s.impl.add(args.a, args.b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// tvInterfaceBIrpcClient implements [tvInterfaceB] interface. It by forwards calls over network to [tvInterfaceBIrpcService] that provides the implementation.
//
// however this one deals with ints
// and also has
//
//multiple lines
/* and some other type of comments
 */
type tvInterfaceBIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func newTvInterfaceBIrpcClient(endpoint irpcgen.Endpoint) (*tvInterfaceBIrpcClient, error) {
	if err := endpoint.RegisterClient(_tvInterfaceBIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &tvInterfaceBIrpcClient{endpoint: endpoint}, nil
}

// add implements [tvInterfaceB]
//
func (_c *tvInterfaceBIrpcClient) add(a int, b int) int {
	var req = _irpc_tvInterfaceB_addReq{
		a: a,
		b: b,
	}
	var resp _irpc_tvInterfaceB_addResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _tvInterfaceBIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

type _irpc_tvInterfaceB_addReq struct {
	a int
	b int
}

func (s _irpc_tvInterfaceB_addReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_tvInterfaceB_addReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type int: %w", err)
	}
	return nil
}

type _irpc_tvInterfaceB_addResp struct {
	p0 int
}

func (s _irpc_tvInterfaceB_addResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_tvInterfaceB_addResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}
