// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/testtools/testservice.go
package testtools

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _TestServiceIrpcId = []byte{
	0xf6, 0xc3, 0x88, 0x37, 0x4d, 0x39, 0xc4, 0xc9,
	0xc0, 0x59, 0xce, 0x55, 0xd0, 0xa7, 0xb3, 0x9d,
	0x25, 0xa8, 0x8f, 0xb4, 0x08, 0xc4, 0xca, 0xf8,
	0xb6, 0xed, 0xe9, 0x42, 0x0c, 0xa7, 0x00, 0x86,
}

type TestServiceIrpcService struct {
	impl TestService
}

func NewTestServiceIrpcService(impl TestService) *TestServiceIrpcService {
	return &TestServiceIrpcService{
		impl: impl,
	}
}
func (s *TestServiceIrpcService) Id() []byte {
	return _TestServiceIrpcId
}
func (s *TestServiceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // Div
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_TestService_DivReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TestService_DivResp
				resp.p0 = s.impl.Div(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 1: // DivErr
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_TestService_DivErrReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TestService_DivErrResp
				resp.p0, resp.p1 = s.impl.DivErr(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 2: // DivCtxErr
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_TestService_DivCtxErrReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TestService_DivCtxErrResp
				resp.p0, resp.p1 = s.impl.DivCtxErr(ctx, args.a, args.b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// TestServiceIrpcClient implements TestService
type TestServiceIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func NewTestServiceIrpcClient(endpoint irpcgen.Endpoint) (*TestServiceIrpcClient, error) {
	if err := endpoint.RegisterClient(_TestServiceIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &TestServiceIrpcClient{endpoint: endpoint}, nil
}
func (_c *TestServiceIrpcClient) Div(a int, b int) int {
	var req = _irpc_TestService_DivReq{
		a: a,
		b: b,
	}
	var resp _irpc_TestService_DivResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _TestServiceIrpcId, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *TestServiceIrpcClient) DivErr(a int, b int) (int, error) {
	var req = _irpc_TestService_DivErrReq{
		a: a,
		b: b,
	}
	var resp _irpc_TestService_DivErrResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _TestServiceIrpcId, 1, req, &resp); err != nil {
		var zero _irpc_TestService_DivErrResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}
func (_c *TestServiceIrpcClient) DivCtxErr(ctx context.Context, a int, b int) (int, error) {
	var req = _irpc_TestService_DivCtxErrReq{
		// ctx: ctx,
		a: a,
		b: b,
	}
	var resp _irpc_TestService_DivCtxErrResp
	if err := _c.endpoint.CallRemoteFunc(ctx, _TestServiceIrpcId, 2, req, &resp); err != nil {
		var zero _irpc_TestService_DivCtxErrResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

type _irpc_TestService_DivReq struct {
	a int
	b int
}

func (s _irpc_TestService_DivReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type int: %w", err)
	}
	return nil
}

type _irpc_TestService_DivResp struct {
	p0 int
}

func (s _irpc_TestService_DivResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	return nil
}

type _irpc_TestService_DivErrReq struct {
	a int
	b int
}

func (s _irpc_TestService_DivErrReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivErrReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type int: %w", err)
	}
	return nil
}

type _irpc_TestService_DivErrResp struct {
	p0 int
	p1 error
}

func (s _irpc_TestService_DivErrResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivErrResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_TestService_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_TestService_impl struct {
	_Error_0_ string
}

func (i _error_TestService_impl) Error() string {
	return i._Error_0_
}

type _irpc_TestService_DivCtxErrReq struct {
	// ctx context.Context
	a int
	b int
}

func (s _irpc_TestService_DivCtxErrReq) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.a); err != nil {
		return fmt.Errorf("serialize \"a\" of type int: %w", err)
	}
	if err := irpcgen.EncInt(e, s.b); err != nil {
		return fmt.Errorf("serialize \"b\" of type int: %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivCtxErrReq) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.a); err != nil {
		return fmt.Errorf("deserialize a of type int: %w", err)
	}
	if err := irpcgen.DecInt(d, &s.b); err != nil {
		return fmt.Errorf("deserialize b of type int: %w", err)
	}
	return nil
}

type _irpc_TestService_DivCtxErrResp struct {
	p0 int
	p1 error
}

func (s _irpc_TestService_DivCtxErrResp) Serialize(e *irpcgen.Encoder) error {
	if err := irpcgen.EncInt(e, s.p0); err != nil {
		return fmt.Errorf("serialize type int: %w", err)
	}
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p1); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivCtxErrResp) Deserialize(d *irpcgen.Decoder) error {
	if err := irpcgen.DecInt(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type int: %w", err)
	}
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_TestService_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p1); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}
