// Code generated by irpc generator; DO NOT EDIT
// Source: github.com/marben/irpc/cmd/irpc/test/testtools/testservice.go
package testtools

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

type TestServiceIrpcService struct {
	impl TestService
	id   []byte
}

func NewTestServiceIrpcService(impl TestService) *TestServiceIrpcService {
	return &TestServiceIrpcService{
		impl: impl,
		id: []byte{
			0x43, 0xf1, 0x04, 0x20, 0xb0, 0x4d, 0xc1, 0xa6,
			0xd3, 0xb9, 0x6d, 0xf3, 0xf9, 0xfd, 0x36, 0xd0,
			0xc5, 0x02, 0x43, 0xd8, 0x7c, 0x77, 0xbf, 0xa0,
			0x5a, 0x7a, 0x9f, 0x0b, 0x11, 0xdd, 0x05, 0x2a,
		},
	}
}
func (s *TestServiceIrpcService) Id() []byte {
	return s.id
}
func (s *TestServiceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // Div
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_TestService_DivReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TestService_DivResp
				resp.p0 = s.impl.Div(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 1: // DivErr
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_TestService_DivErrReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TestService_DivErrResp
				resp.p0, resp.p1 = s.impl.DivErr(args.a, args.b)
				return resp
			}, nil
		}, nil
	case 2: // DivCtxErr
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			// DESERIALIZE
			var args _irpc_TestService_DivCtxErrReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				// EXECUTE
				var resp _irpc_TestService_DivCtxErrResp
				resp.p0, resp.p1 = s.impl.DivCtxErr(ctx, args.a, args.b)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// TestServiceIrpcClient implements TestService
type TestServiceIrpcClient struct {
	endpoint irpcgen.Endpoint
	id       []byte
}

func NewTestServiceIrpcClient(endpoint irpcgen.Endpoint) (*TestServiceIrpcClient, error) {
	id := []byte{
		0x43, 0xf1, 0x04, 0x20, 0xb0, 0x4d, 0xc1, 0xa6,
		0xd3, 0xb9, 0x6d, 0xf3, 0xf9, 0xfd, 0x36, 0xd0,
		0xc5, 0x02, 0x43, 0xd8, 0x7c, 0x77, 0xbf, 0xa0,
		0x5a, 0x7a, 0x9f, 0x0b, 0x11, 0xdd, 0x05, 0x2a,
	}
	if err := endpoint.RegisterClient(id); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &TestServiceIrpcClient{endpoint: endpoint, id: id}, nil
}
func (_c *TestServiceIrpcClient) Div(a int, b int) int {
	var req = _irpc_TestService_DivReq{
		a: a,
		b: b,
	}
	var resp _irpc_TestService_DivResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 0, req, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}
func (_c *TestServiceIrpcClient) DivErr(a int, b int) (int, error) {
	var req = _irpc_TestService_DivErrReq{
		a: a,
		b: b,
	}
	var resp _irpc_TestService_DivErrResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _c.id, 1, req, &resp); err != nil {
		var zero _irpc_TestService_DivErrResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}
func (_c *TestServiceIrpcClient) DivCtxErr(ctx context.Context, a int, b int) (int, error) {
	var req = _irpc_TestService_DivCtxErrReq{
		// ctx: ctx,
		a: a,
		b: b,
	}
	var resp _irpc_TestService_DivCtxErrResp
	if err := _c.endpoint.CallRemoteFunc(ctx, _c.id, 2, req, &resp); err != nil {
		var zero _irpc_TestService_DivCtxErrResp
		return zero.p0, err
	}
	return resp.p0, resp.p1
}

type _irpc_TestService_DivReq struct {
	a int
	b int
}

func (s _irpc_TestService_DivReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int\": %w", err)
	}
	if err := e.VarInt(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int\": %w", err)
	}
	return nil
}

type _irpc_TestService_DivResp struct {
	p0 int
}

func (s _irpc_TestService_DivResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	return nil
}

type _irpc_TestService_DivErrReq struct {
	a int
	b int
}

func (s _irpc_TestService_DivErrReq) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int\": %w", err)
	}
	if err := e.VarInt(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivErrReq) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int\": %w", err)
	}
	return nil
}

type _irpc_TestService_DivErrResp struct {
	p0 int
	p1 error
}

func (s _irpc_TestService_DivErrResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	{
		var isNil bool
		if s.p1 == nil {
			isNil = true
		}
		if err := e.Bool(isNil); err != nil {
			return fmt.Errorf("serialize isNil of type \"bool\": %w", err)
		}

		if !isNil {
			{ // Error()
				_Error_0_ := s.p1.Error()
				if err := e.String(_Error_0_); err != nil {
					return fmt.Errorf("serialize _Error_0_ of type \"string\": %w", err)
				}
			}
		}
	}
	return nil
}
func (s *_irpc_TestService_DivErrResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	{
		var isNil bool
		if err := d.Bool(&isNil); err != nil {
			return fmt.Errorf("deserialize isNil of type \"bool\": %w", err)
		}

		if isNil {
			s.p1 = nil
		} else {
			var impl _error_TestService_impl
			{ // Error()
				if err := d.String(&impl._Error_0_); err != nil {
					return fmt.Errorf("deserialize impl._Error_0_ of type \"string\": %w", err)
				}
			}
			s.p1 = impl
		}
	}
	return nil
}

type _error_TestService_impl struct {
	_Error_0_ string
}

func (i _error_TestService_impl) Error() string {
	return i._Error_0_
}

type _irpc_TestService_DivCtxErrReq struct {
	// ctx context.Context
	a int
	b int
}

func (s _irpc_TestService_DivCtxErrReq) Serialize(e *irpcgen.Encoder) error {
	// no code for context encoding
	if err := e.VarInt(s.a); err != nil {
		return fmt.Errorf("serialize s.a of type \"int\": %w", err)
	}
	if err := e.VarInt(s.b); err != nil {
		return fmt.Errorf("serialize s.b of type \"int\": %w", err)
	}
	return nil
}
func (s *_irpc_TestService_DivCtxErrReq) Deserialize(d *irpcgen.Decoder) error {
	// no code for context decoding
	if err := d.VarInt(&s.a); err != nil {
		return fmt.Errorf("deserialize s.a of type \"int\": %w", err)
	}
	if err := d.VarInt(&s.b); err != nil {
		return fmt.Errorf("deserialize s.b of type \"int\": %w", err)
	}
	return nil
}

type _irpc_TestService_DivCtxErrResp struct {
	p0 int
	p1 error
}

func (s _irpc_TestService_DivCtxErrResp) Serialize(e *irpcgen.Encoder) error {
	if err := e.VarInt(s.p0); err != nil {
		return fmt.Errorf("serialize s.p0 of type \"int\": %w", err)
	}
	{
		var isNil bool
		if s.p1 == nil {
			isNil = true
		}
		if err := e.Bool(isNil); err != nil {
			return fmt.Errorf("serialize isNil of type \"bool\": %w", err)
		}

		if !isNil {
			{ // Error()
				_Error_0_ := s.p1.Error()
				if err := e.String(_Error_0_); err != nil {
					return fmt.Errorf("serialize _Error_0_ of type \"string\": %w", err)
				}
			}
		}
	}
	return nil
}
func (s *_irpc_TestService_DivCtxErrResp) Deserialize(d *irpcgen.Decoder) error {
	if err := d.VarInt(&s.p0); err != nil {
		return fmt.Errorf("deserialize s.p0 of type \"int\": %w", err)
	}
	{
		var isNil bool
		if err := d.Bool(&isNil); err != nil {
			return fmt.Errorf("deserialize isNil of type \"bool\": %w", err)
		}

		if isNil {
			s.p1 = nil
		} else {
			var impl _error_TestService_impl
			{ // Error()
				if err := d.String(&impl._Error_0_); err != nil {
					return fmt.Errorf("deserialize impl._Error_0_ of type \"string\": %w", err)
				}
			}
			s.p1 = impl
		}
	}
	return nil
}
