// Package irpcgen provides functionality for code generated by iRPC tool
//
// This code is not meant to be imported directly by users. Instead, it will be used by the generated *_irpc.go files
package irpcgen
